HEAD-833 move expensive logic to setup instead of mdata:execute where it can timeout

diff --git a/zones/rabbitmq/setup b/zones/rabbitmq/setup
--- a/zones/rabbitmq/setup
+++ b/zones/rabbitmq/setup
@@ -5,6 +5,12 @@
 
 set -o xtrace
 
+if [[ ! -f /var/svc/setup.core ]]; then
+    echo "Fatal: missing /var/svc/setup.core"
+    exit 1
+fi
+source /var/svc/setup.core
+
 echo "Finishing setup of rabbitmq zone"
 
 # Setup .erlang.cookie symlink
