XXX much shell script and spelling cleanup

diff --git a/bin/build-tar-image b/bin/build-tar-image
--- a/bin/build-tar-image
+++ b/bin/build-tar-image
@@ -6,12 +6,35 @@
 #
 
 #
-# Copyright (c) 2014, Joyent, Inc.
+# Copyright 2015 Joyent, Inc.
 #
 
 ROOT=$(cd $(dirname $0)/../; pwd)
 
 . "${ROOT}/buildtools/lib/error_handler.sh"
+
+function usage {
+    if [[ -n "$1" ]]; then
+        echo "ERROR: $1" >&2
+    fi
+    echo "" >&2
+    echo "Usage:" >&2
+    echo "    $0" >&2
+    echo "" >&2
+    exit 1
+}
+
+while getopts 'cr' name; do
+    case "${name}" in
+    c|r)
+        usage "the \"-${name}\" option is no longer supported"
+        ;;
+    \?)
+        usage 'unknown option'
+        ;;
+    esac
+done
+shift $((OPTIND - 1))
 
 # Write output to log file.
 THIS_TIMESTAMP=${TIMESTAMP}
@@ -25,16 +48,7 @@ RONNJS="${ROOT}/buildtools/ronnjs/bin/ronn.js"
 mkdir -p log
 exec > >(tee ${LOGFILE}) 2>&1
 
-if [[ -n ${TRACE} ]]; then
-    if (( BASH_VERSINFO[0] >= 4 && BASH_VERSINFO[1] >= 1 )); then
-        PS4=
-        PS4="${PS4}"'[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: '
-        PS4="${PS4}"'${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-        export PS4
-        export BASH_XTRACEFD=4
-    fi
-    set -o xtrace
-fi
+. "${ROOT}/buildtools/lib/trace_logger.sh"
 
 # Tools.
 if which gawk 2>/dev/null; then
diff --git a/bin/build-usb-image b/bin/build-usb-image
--- a/bin/build-usb-image
+++ b/bin/build-usb-image
@@ -6,42 +6,46 @@
 #
 
 #
-# Copyright (c) 2014, Joyent, Inc.
+# Copyright 2015 Joyent, Inc.
 #
 
-#
-# We set errexit (a.k.a. "set -e") to force an exit on error conditions, but
-# there are many important error conditions that this does not capture --
-# first among them failures within a pipeline (only the exit status of the
-# final stage is propagated).  To exit on these failures, we also set
-# "pipefail" (a very useful option introduced to bash as of version 3 that
-# propagates any non-zero exit values in a pipeline).
-#
+ROOT=$(cd $(dirname $0)/../; pwd)
 
-set -o errexit
-set -o pipefail
+. "${ROOT}/buildtools/lib/error_handler.sh"
 
-if [[ $1 == "-c" ]]; then
-    shift
-    # BASHSTYLED
-    echo "NOTICE: building without config is the only option now, -c is unnecessary."
-fi
+function usage {
+    if [[ -n "$1" ]]; then
+        echo "ERROR: $1" >&2
+    fi
+    echo "" >&2
+    echo "Usage:" >&2
+    echo "    $0 <boot_tarball>" >&2
+    echo "" >&2
+    exit 1
+}
+
+while getopts cr name; do
+    case "${name}" in
+    c)
+        usage 'the "-c" option is no longer supported'
+        ;;
+    \?)
+        usage 'unknown option'
+        ;;
+    esac
+done
+shift $((OPTIND - 1))
 
 function rel2abs () {
-  local abs_path end
-  abs_path=$(unset CDPATH; cd `dirname $1` 2>/dev/null && pwd -P)
-  [[ -z "$abs_path" ]] && return 1
-  end=$(basename $1)
-  echo "${abs_path%*/}/$end"
+    local abs_path end
+    abs_path=$(unset CDPATH; cd `dirname $1` 2>/dev/null && pwd -P)
+    [[ -z "$abs_path" ]] && return 1
+    end=$(basename $1)
+    echo "${abs_path%*/}/$end"
 }
 
 if [[ -z "$1" ]]; then
-    echo "ERROR: no boot tarball supplied"
-    echo ""
-    echo "Usage:"
-    echo "    $0 <boot_tarball>"
-    echo ""
-    exit 1
+    usage 'must provide <boot_tarball> filename'
 fi
 
 TAR_BUILD_FILENAME=$(rel2abs $1)
@@ -51,8 +55,6 @@ TAR_BUILD_IS_DIRECTORY=0
 if [[ -d $TAR_BUILD_FILENAME ]]; then
     TAR_BUILD_IS_DIRECTORY=1
 fi
-
-ROOT=$(cd $(dirname $0)/../; pwd)
 
 # Write output to log file.
 THIS_TIMESTAMP=${TIMESTAMP}
@@ -64,18 +66,7 @@ LOGFILE="${LOGDIR}/build.log.usb.${THIS_TIMESTAMP}"
 mkdir -p log
 exec > >(tee ${LOGFILE}) 2>&1
 
-if [[ $(echo $BASH_VERSION | cut -d '.' -f1-2) > 4.0 ]]; then
-    BASH_IS_NOT_ANCIENT='true'
-fi
-#export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-#set -x
-if [[ `hostname` == "bh1-autobuild" || `hostname` == "bldzone2.joyent.us" \
-      || ! -z $BASH_IS_NOT_ANCIENT ]]; then
-    # BASHSTYLED
-    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-    export BASH_XTRACEFD=4
-    set -o xtrace
-fi
+. "${ROOT}/buildtools/lib/trace_logger.sh"
 
 MERGED_SPEC=
 if [[ -f "${ROOT}/build.spec" && -f "${ROOT}/build.spec.local" ]]; then
