[HEAD-242] pkgsrc-2010q4, gcc45 and bare-1.3.1 upgrade

diff --git a/bin/build-image b/bin/build-image
--- a/bin/build-image
+++ b/bin/build-image
@@ -60,7 +60,8 @@ if [ -z "${PLATFORM_URL}" ]; then
     PLATFORM_URL=${MASTER_PLATFORM_URL}
 fi
 ASSETS_ROOT="https://guest:GrojhykMid@assets.joyent.us/datasets"
-PKGSRC_ROOT="http://pkgsrc.joyent.com/2010Q3/All"
+ASSETS_ROOT_SDC="https://guest:GrojhykMid@assets.joyent.us/templates/sdc/"
+PKGSRC_ROOT="http://pkgsrc.joyent.com/sdc/2010Q4/gcc45/All/"
 
 # Figure out first what we're building, and load the proper include
 
@@ -485,42 +486,56 @@ function get_node_magic
 
 function copy_datasets
 {
-    datasets=( bare-1.2.8 protemplate-2.5.2 nodejs-0.4.0 )
+    datasets=( protemplate-2.5.2 nodejs-0.4.0 )
     mkdir -p  ${STAGE}/datasets
+
+    # bare-1.3.1 is on a different location:
+    copy_dataset 'bare-1.3.1' ${ASSETS_ROOT_SDC}
+
     for dataset in ${datasets[@]}
     do
-        dataset_file="${dataset}.zfs.bz2"
-        if ! bzip2 -t ${ROOT}/cache/${dataset_file}; then
-            echo "==> Corrupt ${dataset_file}, deleting..."
-            rm -f ${ROOT}/cache/${dataset_file}
-        fi
-
-        if [[ ! -f ${ROOT}/cache/${dataset_file} ]]; then
-            if [[ ${HAVE_INTERNET} == "true" ]]; then
-                echo "==> Downloading ${dataset_file}"
-                (cd ${ROOT}/cache && curl --progress-bar -k \
-                    -O ${ASSETS_ROOT}/${dataset_file}) \
-                    || fatal "Unable to download ${dataset_file}"
-            else
-                fatal "Don't have Internet, and don't have valid " \
-                    "${dataset_file}. Can't build."
-            fi
-        fi
-
-        if ! bzip2 -t ${ROOT}/cache/${dataset_file}; then
-            rm -f ${ROOT}/cache/${dataset_file}
-            fatal "Corrupt ${dataset_file}, deleted! Try build again."
-        fi
-
-        echo "==> Copying ${dataset_file}"
-        cp ${ROOT}/cache/${dataset_file} ${STAGE}/datasets/${dataset_file}
-
-        if [[ ${dataset} == "nodejs-0.4.0" ]]; then
-            # the nodejs-0.4.0 dataset is magical and "special" so it needs
-            # more stuff
-            get_node_magic
-        fi
+      copy_dataset ${dataset} ${ASSETS_ROOT}
     done
+}
+
+# This is temporary, until we have all the SDC datasets at the same place.
+# It might be good anyway to add a little check to verify arguments are given.
+function copy_dataset
+{
+  local dataset=$1
+  local dataset_uri=$2
+
+  dataset_file="${dataset}.zfs.bz2"
+  if ! bzip2 -t ${ROOT}/cache/${dataset_file}; then
+      echo "==> Corrupt ${dataset_file}, deleting..."
+      rm -f ${ROOT}/cache/${dataset_file}
+  fi
+
+  if [[ ! -f ${ROOT}/cache/${dataset_file} ]]; then
+      if [[ ${HAVE_INTERNET} == "true" ]]; then
+          echo "==> Downloading ${dataset_file}"
+          (cd ${ROOT}/cache && curl --progress-bar -k \
+              -O ${dataset_uri}/${dataset_file}) \
+              || fatal "Unable to download ${dataset_file}"
+      else
+          fatal "Don't have Internet, and don't have valid " \
+              "${dataset_file}. Can't build."
+      fi
+  fi
+
+  if ! bzip2 -t ${ROOT}/cache/${dataset_file}; then
+      rm -f ${ROOT}/cache/${dataset_file}
+      fatal "Corrupt ${dataset_file}, deleted! Try build again."
+  fi
+
+  echo "==> Copying ${dataset_file}"
+  cp ${ROOT}/cache/${dataset_file} ${STAGE}/datasets/${dataset_file}
+
+  if [[ ${dataset} == "nodejs-0.4.0" ]]; then
+      # the nodejs-0.4.0 dataset is magical and "special" so it needs
+      # more stuff
+      get_node_magic
+  fi
 }
 
 function get_fs_tarball
