Address JBK review comments

diff --git a/bin/build-ipxe b/bin/build-ipxe
--- a/bin/build-ipxe
+++ b/bin/build-ipxe
@@ -44,7 +44,7 @@ function fail()
 boottar=$1
 fullisotar=$2
 
-tdir=$(mktemp -d -p /var/tmp) || fail "mktemp failed!"
+tdir=$(mktemp -d -p /var/tmp) || fail "mktemp (tdir) failed!"
 lofisrcdir=$(mktemp -d -p /var/tmp) || fail "mktemp (lofisrcdir) failed!"
 trap cleanup EXIT
 
@@ -90,11 +90,13 @@ isourl="${baseurl}/$(basename $fullisotar)"
 lofisrcdev=$(pfrun lofiadm -a "$bootarchive")
 pfrun mount -F ufs "$lofisrcdev" "$lofisrcdir"
 # Test domain!  Should pull from environment...
-tfile=$(mktemp)
+tfile=$(mktemp) || fail "mktemp (tfile) failed!"
 echo $testdomain > $tfile
-pfrun mv $tfile "$lofisrcdir"/testdomain.txt
+# Use "cp" here to preserve our tfile reservation.
+pfrun cp -p $tfile "$lofisrcdir"/testdomain.txt
 # URL for full ISO.
 echo $isourl > $tfile
+# Use "mv" here since we are done with tfile.
 pfrun mv $tfile "$lofisrcdir"/isourl.txt
 pfrun chown root:root "$lofisrcdir"/*.txt
 pfrun chmod 0644 "$lofisrcdir"/*.txt
diff --git a/bin/build-iso b/bin/build-iso
--- a/bin/build-iso
+++ b/bin/build-iso
@@ -85,7 +85,10 @@ function create_esp()
 
 	pfrun mkfile -n ${esp_size}m $tmpdir/esp.img
 	bi_esp_blkdev=$(pfexec lofiadm -a $tmpdir/esp.img)
-	[[ $? == 0 ]] || fail "Failed to create ESP lofi device"
+	if [[ $? != 0 ]]; then
+		rm $tmpdir/esp.img
+		fail "Failed to create ESP lofi device"
+	fi
 	readonly esp_rawdev=${bi_esp_blkdev/lofi/rlofi}
 
 	pfrun mkfs -F pcfs -o b=system,size=$esp_sects,nofdisk,fat=32 \
@@ -97,6 +100,7 @@ function create_esp()
 	pfrun cp $bi_protoboot/loader64.efi $efimnt/efi/boot/bootx64.efi
 	pfrun umount $efimnt
 	pfrun lofiadm -d $bi_esp_blkdev
+	rm $tmpdir/esp.img
 }
 
 # - Populate root from the bi_boot_image.
