HEAD-1 README should spell out build instructions, dependencies HEAD-3 zones should be able to specify a URI for their contents HEAD-4 dhcpd and rabbitmq zones should use new fs.uri scheme described in HEAD-3

diff --git a/bin/build-image b/bin/build-image
--- a/bin/build-image
+++ b/bin/build-image
@@ -15,6 +15,12 @@ fi
 ASSETS_ROOT="https://guest:GrojhykMid@assets.joyent.us/templates"
 PKGSRC_ROOT="http://pkgsrc.joyent.com/2010Q3/All"
 
+function fatal
+{
+    echo "$(basename $0): fatal error: $*"
+    exit 1
+}
+
 # Figure out first what we're building, and load the proper include
 
 PLATFORM=$(uname -s)
@@ -172,22 +178,50 @@ function copy_datasets
 
 function copy_zones
 {
-    dhcpd_zonefs="dhcpd.tar.bz2"
-    if [ ! -f "${ROOT}/cache/${dhcpd_zonefs}" ]; then
-        echo "==> Downloading ${dhcpd_zonefs}"
-        (cd ${ROOT}/cache && curl -O ${ASSETS_ROOT}/liveimg/${dhcpd_zonefs})
-    fi
-    mkdir -p ${STAGE}/zones/dhcpd
-    cp ${ROOT}/cache/${dhcpd_zonefs} ${STAGE}/zones/dhcpd/fs.tar.bz2
-    
-    rabbitmq_zonefs="rabbitmq.tar.bz2"
-    if [ ! -f "${ROOT}/cache/${rabbitmq_zonefs}" ]; then
-        echo "==> Downloading ${rabbitmq_zonefs}"
-        (cd ${ROOT}/cache && curl -O ${ASSETS_ROOT}/liveimg/${rabbitmq_zonefs})
-    fi
-    mkdir -p ${STAGE}/zones/rabbitmq
-    cp ${ROOT}/cache/${rabbitmq_zonefs} ${STAGE}/zones/rabbitmq/fs.tar.bz2
-    
+    for zone in $(ls ${STAGE}/zones); do
+        fsuri=${STAGE}/zones/${zone}/fs.uri
+
+        if [ ! -f $fsuri ]; then
+            continue 
+        fi
+
+        #
+        # If we have an fs.uri file, it should be a URI indicating a bzip2'd tar
+        # file; check that the suffix is either ".tbz2" or ".tar.bz2".
+        #
+        uri=`cat $fsuri`
+        suffix=${uri##*.}
+
+        if [ "$suffix" != "tbz2" ]; then
+            prefix=${uri%.*}
+            if [ $suffix != "bz2" ] || [ ${prefix##*.} != "tar" ]; then
+                fatal "$zone: illegal fs.uri: $uri (expected bzip2\'d tarball)"
+            fi
+        fi
+
+        #
+        # If the path has no subdirectory components, then we'll fetch the
+        # file from ${ASSETS_ROOT}.
+        #
+        if [ ${uri%%/*} == $uri ]; then
+            uri=${ASSETS_ROOT}/liveimg/${uri}
+        fi
+        
+        file=${uri##*/}
+
+        echo "==> Downloading $file"
+
+        if [ -f "${ROOT}/cache/$file" ]; then
+            echo "==> (Using cached $file)"
+        else
+            (cd ${ROOT}/cache && curl -fO $uri) || \
+              fatal "could not download $uri for $zone"
+        fi
+
+        mkdir -p ${STAGE}/zones/${zone}
+        cp ${ROOT}/cache/${file} ${STAGE}/zones/${zone}/fs.tar.bz2
+    done
+
     for zone in $(ls ${STAGE}/zones); do
         if [ -x ${STAGE}/zones/${zone}/fs.populate ] && [ -d ${STAGE}/zones/${zone}/fs.root ]; then
             # do in /tmp because only root can write in mnt
