HEAD-857 rearrange configure/setup scripts so that we can have configure re-run every time a smartdc_role zone boots.

diff --git a/zones/assets/user-script b/zones/assets/user-script
--- a/zones/assets/user-script
+++ b/zones/assets/user-script
@@ -4,12 +4,10 @@ set -o xtrace
 
 PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 
-# Only want to run this initial user-script once
-if [[ -f /var/svc/.ran-user-script ]]; then
-    echo "Initial user-script has already been run."
-    exit 0
-fi
-touch /var/svc/.ran-user-script
+fatal() {
+    echo $* >&2
+    exit 1
+}
 
 zone_uuid=$(zonename)
 zone_role=$(mdata-get sdc:tags.smartdc_role)
@@ -17,6 +15,36 @@ if [[ -z ${zone_role} ]]; then
     echo "Unable to find zone role in metadata."
     exit 1
 fi
+
+if [[ ! -d /opt/smartdc/etc ]]; then
+    mkdir -p /opt/smartdc/etc
+fi
+if [[ -f /assets/extra/${zone_role}/zoneconfig ]]; then
+    cp /assets/extra/${zone_role}/zoneconfig /opt/smartdc/etc/zoneconfig || \
+        fatal "unable to copy zoneconfig file"
+fi
+touch /opt/smartdc/etc/zoneconfig
+
+mkdir -p /opt/smartdc/bin
+for file in configure backup restore setup; do
+    if [[ -f /assets/extra/${zone_role}/${file} ]]; then
+        cp /assets/extra/${zone_role}/${file} /opt/smartdc/bin/${file}
+    fi
+done
+chmod 755 /opt/smartdc/bin/*
+
+# Run the configure whenever we didn't do setup already
+if [[ -f /var/svc/setup_complete ]]; then
+    # We already did setup (which ran configure last time), so just reconfigure
+    /opt/smartdc/bin/configure
+fi
+
+# Only want to run this initial user-script once
+if [[ -f /var/svc/.ran-user-script ]]; then
+    echo "Initial user-script has already been run."
+    exit 0
+fi
+touch /var/svc/.ran-user-script
 
 pkgsrc_lst=$(ls -1 /assets/extra/${zone_role}/pkgsrc_*)
 pkgsrc_tar=/assets/extra/pkgsrc/$(basename ${pkgsrc_lst}).tar
@@ -33,16 +61,10 @@ do
 done
 rm -rf /var/svc/pkgs
 
-mkdir -p /opt/smartdc/bin
-for file in configure configure.sh backup restore setup; do
-    if [[ -f /assets/extra/${zone_role}/${file} ]]; then
-        cp /assets/extra/${zone_role}/${file} /opt/smartdc/bin/${file}
-    fi
-done
-chmod 755 /opt/smartdc/bin/*
-
-if [[ -f /opt/smartdc/bin/setup ]]; then
-    bash /opt/smartdc/bin/setup >/var/svc/setup.log 2>&1 &
+bash /opt/smartdc/bin/setup >/var/svc/setup.log 2>&1 &
+if [[ $? != 0 ]]; then
+    echo "Failed to setup zone"
+    exit 1
 fi
 
 exit 0
diff --git a/zones/cloudapi/setup b/zones/cloudapi/setup
--- a/zones/cloudapi/setup
+++ b/zones/cloudapi/setup
@@ -1,259 +1,32 @@
 #!/usr/bin/bash
+#
+# Copyright (c) 2011 Joyent Inc., All rights reserved.
+#
 
-# This script runs with the $CONFIG_assets_ip variable set to the assets zone
-# IP address.  Its up to this script to pull down the rest of the files it
-# needs from the assets zone and setup the zone for the given role.  This
-# script is run in the background by the mdata svc so its ok if it takes
-# a little while to install all of the pkgs.
+set -o xtrace
 
 PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 
-role=cloudapi
-app_name=$role
-
-cd /var/svc
-
-curl -k -o zoneconfig -s $CONFIG_assets_ip:/extra/$role/zoneconfig
-curl -k -o hn_config -s $CONFIG_assets_ip:/extra/$role/hn_config
-curl -k -o hn_generic -s $CONFIG_assets_ip:/extra/$role/hn_generic
-
-# We need some of the headnode config, but don't leave the files around
-. /var/svc/hn_config
-. /var/svc/hn_generic
-rm -f /var/svc/hn_config /var/svc/hn_generic
-# Load up the config values
-. /var/svc/zoneconfig
-
-# The user-script is downloaded and executed on every zone boot. We take
-# advantage of this to maintain the cached config values post-setup.
-if [ -e /var/svc/setup_complete ]; then
-	oldpw=`nawk '{
-	    if (! done && $1 == "\"password\":") {
-		print substr($2, 2, length($2) - 3)
-		done = 1
-	    }
-	}' /opt/smartdc/cloudapi/cfg/config.json`
-	[ "$cloudapi_http_admin_pw" == "$oldpw" ] && exit 0
-
-	echo "Updating cloudapi configuration"
-	nawk -v p=$cloudapi_http_admin_pw '{
-	    if (! done && $1 == "\"password\":") {
-		printf("  \"password\": \"%s\",\n", p)
-		done = 1
-	    } else {
-		print $0
-	    }
-	}' /opt/smartdc/cloudapi/cfg/config.json \
-	 > /opt/smartdc/cloudapi/cfg/config.json.new
-	mv /opt/smartdc/cloudapi/cfg/config.json.new \
-	   /opt/smartdc/cloudapi/cfg/config.json
-	svcadm restart cloudapi
-	exit 0
-fi
-
-# Setup the zone
-curl -k -o pkgsrc -s $CONFIG_assets_ip:/extra/$role/pkgsrc_2010q4
-curl -k -o fs.tar.bz2 -s $CONFIG_assets_ip:/extra/$role/fs.tar.bz2
-curl -k -o pkgsrc.tar -s $CONFIG_assets_ip:/extra/pkgsrc/pkgsrc_2010q4.tar
+# This includes the fatal function and downloads and installs files.
+source /var/svc/setup.common
 
 # Cookie to identify this as a SmartDC zone and its role
 mkdir -p /var/smartdc/cloudapi
-
-# Unpack fs.tar and copy files into proper locations within the zone
-mkdir /.stage
 mkdir -p /opt/smartdc/cloudapi/ssl
-echo "unpack fs.tar"
-(cd /.stage; bzcat /var/svc/fs.tar.bz2 | tar xbf 512 -)
-rm -f /var/svc/fs.tar.bz2
-#echo "install root"
-(cd /.stage/root; tar cbf 512 - *) | (cd /opt/smartdc/cloudapi; tar xbf 512 -)
-#echo "install site"
-#(cd /.stage/site; tar cbf 512 - *) | (cd /lib/svc/manifest/site; tar xbf 512 -)
-#rm -rf /.stage
-
-# Install using local pkg repo
-mkdir -p /var/svc/pkgs
-(cd /var/svc/pkgs && tar -xf /var/svc/pkgsrc.tar \
-      $(cat /var/svc/pkgsrc | sed -e "s/$/.tgz/" | xargs))
-rm -f /var/svc/pkgsrc.tar
-
-for i in `cat /var/svc/pkgsrc`
-do
-	echo "Installing $i" 
-	pkg_info $i >/dev/null 2>&1 || pkg_add -f /var/svc/pkgs/$i
-done
-rm -rf /var/svc/pkgs
-
-# XXX is net1 external nic?
-EXT_IPADDR=`ifconfig net1 | nawk '{if ($1 == "inet") print $2}'`
-CLOUDAPI_EXTERNAL_URL="https://$EXT_IPADDR"
 
 echo "Installing local node.js"
 mkdir -p /opt/smartdc/cloudapi/cfg
 cd -
 /usr/bin/chown -R root:root /opt/smartdc
 
-
 echo "Generating SSL Certificate"
 /opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/cloudapi/ssl/key.pem -out /opt/smartdc/cloudapi/ssl/cert.pem -days 365
 
-echo "Creating SMF manifest"
-cat > /opt/smartdc/cloudapi/cloudapi_manifest.xml <<HERE
-<?xml version="1.0"?>
-<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
-<service_bundle type="manifest" name="cloudapi">
-  <service name="smartdc/site/cloudapi" type="service" version="6.1.0">
-
-    <create_default_instance enabled="true"/>
-    <single_instance/>
-
-    <dependency name="network" grouping="require_all" restart_on="error" type="service">
-      <service_fmri value="svc:/milestone/network:default"/>
-    </dependency>
-
-    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
-      <service_fmri value="svc:/system/filesystem/local"/>
-    </dependency>
-
-    <exec_method
-      type="method"
-      name="start"
-      exec="/opt/smartdc/node/bin/node /opt/smartdc/cloudapi/server.js &amp;"
-      timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/cloudapi">
-        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
-        <method_environment>
-          <envvar name="PATH" value="/opt/smartdc/node/bin:/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
-          <envvar name="LD_PRELOAD_32" value="/usr/lib/extendedFILE.so.1" />
-        </method_environment>
-      </method_context>
-    </exec_method>
-
-    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/cloudapi" />
-    </exec_method>
-
-    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/cloudapi" />
-    </exec_method>
-
-    <property_group name="startd" type="framework">
-      <propval name="ignore_error" type="astring" value="core,signal"/>
-    </property_group>
-
-    <property_group name="application" type="application">
-
-    </property_group>
-
-    <stability value="Stable"/>
-
-    <template>
-      <common_name>
-        <loctext xml:lang="C">Cloudapi daemon (node)</loctext>
-      </common_name>
-    </template>
-
-  </service>
-
-</service_bundle>
-HERE
-
-cat > /opt/smartdc/cloudapi/cfg/config.json <<HERE
-{
-  "siteName": "${CLOUDAPI_EXTERNAL_URL}",
-  "port": 443,
-  "cert": "./ssl/cert.pem",
-  "key": "./ssl/key.pem",
-  "logLevel": "Info",
-  "ufds": {
-    "url": "${UFDS_URL}",
-    "bindDN": "${UFDS_ROOT_DN}",
-    "bindPassword": "${UFDS_ROOT_PW}",
-    "cache": {
-      "size": 1000,
-      "expiry": 300
-    }
-  },
-  "mapi": {
-    "uri": "${MAPI_URL}",
-    "username": "${MAPI_HTTP_ADMIN_USER}",
-    "password": "${MAPI_HTTP_ADMIN_PW}",
-    "datasetCache": {
-      "size": 100,
-      "expiry": 300
-    },
-    "pkgCache": {
-      "size": 100,
-      "expiry": 60
-    }
-  },
-  "ca": {
-    "uri": "${CA_URL}"
-  },
-  "rabbitmq": {
-    "host": "${RABBIT_IP}",
-    "user": "guest",
-    "password": "guest",
-    "vhost": "/"
-  },
-  "datacenters": {
-    "${DATACENTER_NAME}": "${CLOUDAPI_EXTERNAL_URL}"
-  },
-  "preProvisionHook": {
-    "plugin": "./plugins/capi_limits",
-    "enabled": true,
-    "config": {
-      "datacenter": "${DATACENTER_NAME}",
-      "defaults": {
-        "smartos": 1,
-        "nodejs": 1,
-        "ubuntu": 1
-      }
-    }
-  },
-  "postProvisionHook": {
-    "plugin": "./plugins/machine_email",
-    "enabled": false,
-    "config": {
-      "sendmail": "/opt/local/sbin/sendmail -i",
-      "from": "support@joyent.com",
-      "subject": "Your SmartDataCenter machine is provisioning",
-      "body": "Check /my/machines for updates"
-    }
-  },
-  "userThrottles": {
-    "all": {
-      "username": true,
-      "burst": 30,
-      "rate": 10,
-      "overrides": {
-        "${CAPI_ADMIN_LOGIN}": {
-          "burst": 0,
-          "rate": 0
-        }
-      }
-    },
-    "analytics": {
-      "username": true,
-      "burst": 1000,
-      "rate": 100,
-      "overrides": {
-        "${CAPI_ADMIN_LOGIN}": {
-          "burst": 0,
-          "rate": 0
-        }
-      }
-    }
-  }
-}
-HERE
-
-echo Importing cloudapi_manifest.xml
-/usr/sbin/svccfg import /opt/smartdc/cloudapi/cloudapi_manifest.xml
-
-echo Enablig service cloudapi
-/usr/sbin/svcadm enable smartdc/site/cloudapi
+# do configuration now.
+/opt/smartdc/bin/configure || fatal "Unable to configure cloudapi zone"
 
 touch /var/svc/setup_complete
 echo "setup done"
 (sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &
+
+exit 0
diff --git a/zones/dhcpd/setup b/zones/dhcpd/setup
--- a/zones/dhcpd/setup
+++ b/zones/dhcpd/setup
@@ -5,18 +5,16 @@
 
 set -o xtrace
 
-if [[ ! -f /var/svc/setup.core ]]; then
-    echo "Fatal: missing /var/svc/setup.core"
-    exit 1
-fi
-source /var/svc/setup.core
+# This includes the fatal function and downloads and installs files.
+source /var/svc/setup.common
 
 echo "Finishing setup of dhcpd zone"
 
 # Apply configuration from /opt/smartdc/etc/zoneconfig now
-source /opt/smartdc/bin/configure.sh
+/opt/smartdc/bin/configure || fatal "Unable to configure zone"
 
 touch /var/svc/setup_complete
 echo "setup done"
 (sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &
 
+exit 0
diff --git a/zones/mapi/setup b/zones/mapi/setup
--- a/zones/mapi/setup
+++ b/zones/mapi/setup
@@ -5,15 +5,14 @@
 
 set -o xtrace
 
-if [[ ! -f /var/svc/setup.core ]]; then
-    echo "Fatal: missing /var/svc/setup.core"
-    exit 1
-fi
-source /var/svc/setup.core
+# This includes the fatal function and downloads and installs files.
+source /var/svc/setup.common
 
 echo "Finishing setup of MAPI zone"
 
-app_name='mapi'
+zone_uuid=$(zonename)
+zone_role="mapi"
+app_name=${zone_role}
 
 #
 # symlink_ruby() just creates missing symlinks to ruby18 and irb18 on zones
@@ -65,15 +64,6 @@ function create_jill_account
 # Setup datasets this logic comes from the old zone-datasets and
 # 95-zone-dataset.sh files
 #
-
-# ASSETS_IP is set by user-script before calling us.
-zone_uuid=$(zonename)
-zone_role=$(mdata-get sdc:tags.smartdc_role)
-
-if [[ -z ${zone_role} ]]; then
-    echo "Failed to find zone role in metadata."
-    exit 1
-fi
 
 echo "Configuring ${zone_role}..."
 
@@ -176,216 +166,18 @@ echo "Updating postgresql stop method"
 $(/opt/local/bin/gsed -i"" -e "s/\$PGDATA stop/\$PGDATA stop -m fast/" /opt/local/share/smf/method/svc-pgsql90)
 
 # Apply configuration from /opt/smartdc/etc/zoneconfig now
-source /opt/smartdc/bin/configure.sh
+/opt/smartdc/bin/configure || fatal "Unable to configure zone"
 
-# setup compute node's config file (configure.sh loaded zoneconfig vars for us)
-# The values must exist in the zoneconfig for them to be avaliable here.
+eval $(cat /opt/smartdc/etc/zoneconfig)
 
-mkdir -p /opt/smartdc/node.config
-cat >/opt/smartdc/node.config/node.config <<EOF
-datacenter_name='${DATACENTER_NAME}'
-root_authorized_keys_file='${ROOT_AUTHORIZED_KEYS_FILE}'
-assets_admin_ip='${ASSETS_IP}'
-ntp_hosts='${COMPUTE_NODE_NTP_HOSTS}'
-swap='${COMPUTE_NODE_SWAP}'
-rabbitmq='${RABBITMQ}'
-root_shadow='${ROOT_SHADOW}'
-ufds_admin_ip='${UFDS_ADMIN_IP}'
-ufds_admin_uuid='${UFDS_ADMIN_UUID}'
-dhcp_lease_time='${DHCP_LEASE_TIME}'
-capi_client_url='${CAPI_CLIENT_URL}'
-capi_http_admin_user='${CAPI_HTTP_ADMIN_USER}'
-capi_http_admin_pw='${CAPI_HTTP_ADMIN_PW}'
-mapi_client_url='${MAPI_CLIENT_URL}'
-mapi_http_admin_user='${HTTP_ADMIN_USER}'
-mapi_http_admin_pw='${HTTP_ADMIN_PW}'
-zonetracker_database_path='${ZONETRACKER_DATABASE_PATH}'
-EOF
+# Calculate the bitcounts
+source /lib/sdc/network.sh
+ADMIN_CIDR=$(ip_netmask_to_cidr ${ADMIN_NETWORK} ${ADMIN_NETMASK})
+ADMIN_BITCOUNT=${ADMIN_CIDR##*/}
+EXTERNAL_CIDR=$(ip_netmask_to_cidr ${EXTERNAL_NETWORK} ${EXTERNAL_NETMASK})
+EXTERNAL_BITCOUNT=${EXTERNAL_CIDR##*/}
 
-# Pull down authorized_keys file if it's there
-curl -o /opt/smartdc/node.config/${ROOT_AUTHORIZED_KEYS_FILE} -s -S -f \
-    http://${ASSETS_IP}/extra/${zone_role}/config.inc/${ROOT_AUTHORIZED_KEYS_FILE}
-
-# Generate the agents setup script:
-
-AGENTS_FILE_VERSION=$(ls -1t /opt/smartdc/agent-scripts/ | grep '^agents-.*\.sh' | grep -v -- "-hvm-" | head -n1)
-
-echo "Generating agents setup file at '/opt/smartdc/mapi-data/setup_agents.sh'"
-
-cat > /opt/smartdc/mapi-data/setup_agents.sh <<AGENTS
-#!/usr/bin/bash
-#
-# Copyright (c) 2011 Joyent Inc., All rights reserved.
-#
-
-PATH=/usr/bin:/usr/sbin:/bin:/sbin
-export PATH
-
-fatal()
-{
-    # Any error message should be redirected to stderr:
-    echo "Error: \$1" 1>&2
-    exit 1
-}
-
-
-setup_agents()
-{
-  cd /var/tmp
-
-  AGENTS_SHAR=\$1
-
-  if [[ -z \${AGENTS_SHAR} ]]; then
-    AGENTS_SHAR="${AGENTS_FILE_VERSION}"
-  fi
-
-  /usr/bin/curl --silent --show-error -O http://${PRIVATE_IP}/ur-scripts/\${AGENTS_SHAR}
-
-  if [[ ! -f /var/tmp/\${AGENTS_SHAR} ]]; then
-    fatal "failed to download agents setup script"
-  fi
-
-  mkdir -p /opt/smartdc/agents/log
-  /usr/bin/bash /var/tmp/\${AGENTS_SHAR} &>/opt/smartdc/agents/log/install.log
-  result=\$(tail -n 1 /opt/smartdc/agents/log/install.log)
-
-  if [[ "\$result" == "npm not ok" ]]; then
-    tail -n 10 /opt/smartdc/agents/log/install.log >&2
-    exit 1
-  else
-    tail -n 10 /opt/smartdc/agents/log/install.log >&2
-  fi
-}
-
-
-if [[ ! -d /opt/smartdc/agents/bin ]]; then
-  setup_agents \$1
-fi
-
-# Return SmartDC services statuses on STDOUT:
-echo \$(svcs -a -o STATE,FMRI|grep smartdc)
-
-# Scripts to be executed by Ur need to explicitly return an exit status code:
-exit 0
-
-AGENTS
-
-
-
-# Generate the reboot server script:
-
-echo "Generating reboot server file at '/opt/smartdc/mapi-data/reboot_server.sh'"
-
-cat > /opt/smartdc/mapi-data/reboot_server.sh <<REBOOT
-#!/usr/bin/bash
-#
-# Copyright (c) 2011 Joyent Inc., All rights reserved.
-#
-
-PATH=/usr/bin:/usr/sbin
-export PATH
-
-# Scripts to be executed by Ur need to explicitly return an exit status code.
-exit 113
-
-REBOOT
-
-echo "Creating $app_name-setup service"
-
-cat >"/lib/svc/manifest/site/$app_name-setup.xml" <<SETUP_SMF
-<?xml version='1.0'?>
-<!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
-<service_bundle type='manifest' name='export'>
-  <service name='platform/smartdc/${app_name}-setup' type='service' version='0'>
-    <create_default_instance enabled='true'/>
-    <single_instance/>
-    <dependency name='filesystem' grouping='require_all' restart_on='error' type='service'>
-      <service_fmri value='svc:/system/filesystem/local'/>
-    </dependency>
-    <exec_method name='start' type='method' exec='/opt/smartdc/$app_name-data/$app_name-setup-service.sh' timeout_seconds='180'>
-      <method_context>
-        <method_credential user='root' group='root'/>
-      </method_context>
-    </exec_method>
-    <exec_method name='stop' type='method' exec=':true' timeout_seconds='0'/>
-    <property_group name='application' type='application'/>
-    <property_group name='startd' type='framework'>
-      <propval name='duration' type='astring' value='transient'/>
-    </property_group>
-    <stability value='Evolving'/>
-    <template>
-      <common_name>
-        <loctext xml:lang='C'>SmartDC Setup service ($app_name)</loctext>
-      </common_name>
-    </template>
-  </service>
-</service_bundle>
-SETUP_SMF
-
-echo "Creating SMF manifest for ssagent"
-
-cat > /opt/smartdc/mapi/ssagent/ssagent.smf <<HERE
-<?xml version="1.0"?>
-<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
-<service_bundle type="manifest" name="ssagent">
-  <service name="smartdc/app/ssagent" type="service" version="6.1.0">
-
-    <create_default_instance enabled="true"/>
-    <single_instance/>
-
-    <dependency name="network" grouping="require_all" restart_on="error" type="service">
-      <service_fmri value="svc:/milestone/network:default"/>
-    </dependency>
-
-    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
-      <service_fmri value="svc:/system/filesystem/local"/>
-    </dependency>
-
-    <exec_method
-      type="method"
-      name="start"
-      exec="/usr/bin/node /opt/smartdc/mapi/ssagent/ssagent.js &amp;"
-      timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/mapi/ssagent">
-        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
-        <method_environment>
-          <envvar name="AMQP_HOST" value="${RABBITMQ_PRIVATE_IP}"/>
-          <envvar name="PATH" value="/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
-          <envvar name="LD_PRELOAD_32" value="/usr/lib/extendedFILE.so.1" />
-        </method_environment>
-      </method_context>
-    </exec_method>
-
-    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/mapi/ssagent" />
-    </exec_method>
-
-    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/mapi/ssagent" />
-    </exec_method>
-
-    <property_group name="startd" type="framework">
-      <propval name="ignore_error" type="astring" value="core,signal"/>
-    </property_group>
-
-    <property_group name="application" type="application">
-
-    </property_group>
-
-    <stability value="Stable"/>
-
-    <template>
-      <common_name>
-        <loctext xml:lang="C">Screenshot Agent Daemon (node)</loctext>
-      </common_name>
-    </template>
-
-  </service>
-
-</service_bundle>
-HERE
-
-
+echo "Creating service setup script."
 cat > "/opt/smartdc/$app_name-data/$app_name-setup-service.sh" <<SETUP_SERVICE
 #!/usr/bin/bash
 
@@ -528,7 +320,9 @@ echo "$POSTGRES_PW" > /tmp/pgpasswd
     ADMIN_BITCOUNT="$ADMIN_BITCOUNT" \
     ADMIN_GATEWAY="$ADMIN_GATEWAY" \
     ADMIN_IP="$ADMIN_IP" \
+    ADMIN_UUID="$UFDS_ADMIN_UUID" \
     ADMIN_VLAN_ID="$ADMIN_VLAN_ID" \
+    DATASETS="$DATASETS" \
     EXTERNAL_NETWORK="$EXTERNAL_NETWORK" \
     EXTERNAL_BITCOUNT="$EXTERNAL_BITCOUNT" \
     EXTERNAL_GATEWAY="$EXTERNAL_GATEWAY" \
@@ -565,8 +359,6 @@ SETUP_SERVICE
 
 chmod +x "/opt/smartdc/$app_name-data/$app_name-setup-service.sh"
 
-
-
 # Ensure everything in /opt/smartdc is owned by jill
 chown -R jill:jill /opt/smartdc
 
@@ -578,3 +370,4 @@ touch /var/svc/setup_complete
 echo "setup done"
 (sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &
 
+exit 0
diff --git a/zones/redis/setup b/zones/redis/setup
--- a/zones/redis/setup
+++ b/zones/redis/setup
@@ -1,100 +1,33 @@
 #!/usr/bin/bash
+#
+# Copyright (c) 2011 Joyent Inc., All rights reserved.
+#
 
-# This script runs with the $CONFIG_assets_ip variable set to the assets zone
-# IP address.  Its up to this script to pull down the rest of the files it
-# needs from the assets zone and setup the zone for the given role.  This
-# script is run in the background by the mdata svc so its ok if it takes
-# a little while to install all of the pkgs.
+set -o xtrace
 
 PATH=/opt/redis/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 
-role=redis
-
-cd /var/svc
-
-curl -k -o zoneconfig -s $CONFIG_assets_ip:/extra/$role/zoneconfig
-curl -k -o hn_config -s $CONFIG_assets_ip:/extra/$role/hn_config
-curl -k -o hn_generic -s $CONFIG_assets_ip:/extra/$role/hn_generic
-
-# We need some of the headnode IP addrs, but don't leave the file around
-. /var/svc/hn_config
-. /var/svc/hn_generic
-rm -f /var/svc/hn_config
-# Load up the config values
-. /var/svc/zoneconfig
-
-# The user-script is downloaded and executed on every zone boot. We take
-# advantage of this to maintain the cached config values post-setup.
-if [ -e /var/svc/setup_complete ]; then
-	exit 0
-fi
-
-# Setup the zone
-curl -o pkgsrc -s $CONFIG_assets_ip:/extra/$role/pkgsrc_2011q2_64
-curl -o fs.tar.bz2 -s $CONFIG_assets_ip:/extra/$role/fs.tar.bz2
-curl -o pkgsrc.tar -s $CONFIG_assets_ip:/extra/pkgsrc/pkgsrc_2011q2_64.tar
-curl -o redis-2.4.1.tar.bz2 -s $CONFIG_assets_ip:/extra/$role/redis-2.4.1.tar.bz2
+# This includes the fatal function and downloads and installs files.
+source /var/svc/setup.common
 
 # Cookie to identify this as a SmartDC zone and its role
 mkdir -p /var/smartdc/redis
-
-# Unpack fs.tar and copy files into proper locations within the zone
-mkdir /.stage
-echo "unpack fs.tar"
-(cd /.stage; bzcat /var/svc/fs.tar.bz2 | tar xbf 512 -)
-rm -f /var/svc/fs.tar.bz2
-echo "install root"
-(cd /.stage/root; tar cbf 512 - *) | (cd /; tar xbf 512 -)
-rm -rf /.stage
-
-# Install using local pkg repo
-mkdir -p /var/svc/pkgs
-(cd /var/svc/pkgs && tar -xf /var/svc/pkgsrc.tar \
-      $(cat /var/svc/pkgsrc | sed -e "s/$/.tgz/" | xargs))
-rm -f /var/svc/pkgsrc.tar
-
-for i in `cat /var/svc/pkgsrc`
-do
-	echo "Installing $i"
-	pkg_info $i >/dev/null 2>&1 || pkg_add -f /var/svc/pkgs/$i
-done
-rm -rf /var/svc/pkgs
 
 # Install Redis
 cd /opt
 /usr/bin/gtar -jxf /var/svc/redis-2.4.1.tar.bz2
 mkdir -p /var/db/redis /var/log/redis
-
 /usr/sbin/groupadd redis
 /usr/sbin/useradd -d /opt/redis -s /usr/bin/bash -g redis redis
 /usr/bin/passwd -l redis
 /usr/sbin/projadd -c "Redis Tunings" -K "process.max-file-descriptor=(basic,65535,deny),(priv,65535,deny)" -U redis -G redis redis
 /usr/bin/chown -R redis:redis /opt/redis /var/db/redis /var/log/redis
-
-
-# Write redis config.
-cat >/opt/redis/etc/redis.conf <<CONFIG
-daemonize yes
-pidfile /var/run/redis.pid
-# "port 6379" is the default
-loglevel notice
-logfile /var/log/redis/redis.log
-# Snapshotting:
-#   after 60 sec if at least 1 key changed
-# Default of only every 15 *minutes* for 1 key change is too long for us here.
-save 60 1
-dir /var/db/redis
-CONFIG
-
-
 rm -f /var/svc/redis-2.4.1.tar.bz2
 
-svccfg import /var/tmp/redis.smf
-svcadm enable redis
-sleep 5
-
-svcs redis
+/opt/smartdc/bin/configure || fatal "Unable to configure zone."
 
 touch /var/svc/setup_complete
 echo "setup done"
 (sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &
+
+exit 0
diff --git a/zones/riak/setup b/zones/riak/setup
--- a/zones/riak/setup
+++ b/zones/riak/setup
@@ -1,98 +1,37 @@
 #!/usr/bin/bash
+#
+# Copyright (c) 2011 Joyent Inc., All rights reserved.
+#
 
-# This script runs with the $CONFIG_assets_ip variable set to the assets zone
-# IP address.  Its up to this script to pull down the rest of the files it
-# needs from the assets zone and setup the zone for the given role.  This
-# script is run in the background by the mdata svc so its ok if it takes
-# a little while to install all of the pkgs.
+set -o xtrace
 
 PATH=/opt/riak/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 
-# Just update this whenever you update the riak tarball in the directory, the
-# rest of the script can remain untouched
-RIAK_VERSION=1.0.2
+# This includes the fatal function and downloads and installs files.
+source /var/svc/setup.common
 
-role=riak
-
-cd /var/svc
-
-curl -k -o zoneconfig -s $CONFIG_assets_ip:/extra/$role/zoneconfig
-curl -k -o hn_config -s $CONFIG_assets_ip:/extra/$role/hn_config
-curl -k -o hn_generic -s $CONFIG_assets_ip:/extra/$role/hn_generic
-
-# We need some of the headnode IP addrs, but don't leave the file around
-. /var/svc/hn_config
-. /var/svc/hn_generic
-rm -f /var/svc/hn_config
-# Load up the config values
-. /var/svc/zoneconfig
-
-# The user-script is downloaded and executed on every zone boot. We take
-# advantage of this to maintain the cached config values post-setup.
-if [ -e /var/svc/setup_complete ]; then
-	echo RIAK_COOKIE=$RIAK_COOKIE >/opt/smartdc/etc/zoneconfig
-	exit 0
-fi
-
-# Setup the zone
-curl -o pkgsrc -s $CONFIG_assets_ip:/extra/$role/pkgsrc_2011q2_64
-curl -o fs.tar.bz2 -s $CONFIG_assets_ip:/extra/$role/fs.tar.bz2
-curl -o pkgsrc.tar -s $CONFIG_assets_ip:/extra/pkgsrc/pkgsrc_2011q2_64.tar
-    $CONFIG_assets_ip:/extra/$role/riak-$RIAK_VERSION.tar.bz2
+# Load this for RIAK_VERSION AND RIAK_ADMIN_IP*
+eval $(cat /opt/smartdc/etc/zoneconfig)
 
 # Cookie to identify this as a SmartDC zone and its role
 mkdir -p /var/smartdc/riak
-
-# Unpack fs.tar and copy files into proper locations within the zone
-mkdir /.stage
-echo "unpack fs.tar"
-(cd /.stage; bzcat /var/svc/fs.tar.bz2 | tar xbf 512 -)
-rm -f /var/svc/fs.tar.bz2
-echo "install root"
-(cd /.stage/root; tar cbf 512 - *) | (cd /; tar xbf 512 -)
-rm -rf /.stage
-
-# Install using local pkg repo
-mkdir -p /var/svc/pkgs
-(cd /var/svc/pkgs && tar -xf /var/svc/pkgsrc.tar \
-      $(cat /var/svc/pkgsrc | sed -e "s/$/.tgz/" | xargs))
-rm -f /var/svc/pkgsrc.tar
-
-for i in `cat /var/svc/pkgsrc`
-do
-	echo "Installing $i"
-	pkg_info $i >/dev/null 2>&1 || pkg_add -f /var/svc/pkgs/$i
-done
-rm -rf /var/svc/pkgs
-
 mkdir -p /opt/smartdc/etc
-echo RIAK_COOKIE=$RIAK_COOKIE >/opt/smartdc/etc/zoneconfig
 
 # Install Riak
 cd /opt
 /usr/bin/gtar -jxf /var/svc/riak.tar.bz2
 mkdir -p /var/db/riak /var/log/riak
-
 /usr/sbin/groupadd riak
 /usr/sbin/useradd -d /opt/riak -s /usr/bin/bash -g riak riak
 /usr/bin/passwd -l riak
 /usr/sbin/projadd -c "Riak 1.0 Tunings" -K "process.max-file-descriptor=(basic,65535,deny),(priv,65535,deny)" -U riak -G riak riak
 /usr/bin/chown -R riak:riak /opt/riak /var/db/riak /var/log/riak
-
 rm -f /var/svc/riak.tar.bz2
-
-# Update RIAK node name and cluster cookie
-IPADDR=`/usr/sbin/ifconfig net0 | /usr/bin/nawk '/inet/ {print $2}'`
-gsed -i -e s/127.0.0.1/$IPADDR/ /opt/riak/etc/app.config
-
-gsed -i -e "s/riak@127.0.0.1/riak@$IPADDR/" /opt/riak/etc/vm.args
-gsed -i -e "s/setcookie riak/setcookie $RIAK_COOKIE/" /opt/riak/etc/vm.args
 
 echo "Generating SSL Certificate"
 /opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/riak/etc/key.pem -out /opt/riak/etc/cert.pem -days 3650
 
-svccfg import /opt/riak/etc/riak_smf_manifest.xml
-svcadm enable riak
+/opt/smartdc/bin/configure || fatal "Unable to complete configuration of riak zone."
 
 # Wait up to 3 minutes for riak svc to be ready
 cnt=0
@@ -107,7 +46,7 @@ done
 
 # If not the first riak zone, then join the existing cluster.
 join_riak_ips=`set | nawk -F= -v myaddr=$IPADDR \
-    '/^riak_admin_ip/ {if ($2 != myaddr) print $2}'`
+    '/^RIAK_ADMIN_IP/ {if ($2 != myaddr) print $2}'`
 for i in $join_riak_ips
 do
 	# HOME must be set for 'erlexec' (used in riak-admin)
@@ -120,3 +59,5 @@ done
 touch /var/svc/setup_complete
 echo "setup done"
 (sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &
+
+exit 0
diff --git a/zones/ufds/setup b/zones/ufds/setup
--- a/zones/ufds/setup
+++ b/zones/ufds/setup
@@ -1,67 +1,27 @@
 #!/usr/bin/bash
+#
+# Copyright (c) 2011 Joyent Inc., All rights reserved.
+#
 
-# This script runs with the $CONFIG_assets_ip variable set to the assets zone
-# IP address.  Its up to this script to pull down the rest of the files it
-# needs from the assets zone and setup the zone for the given role.  This
-# script is run in the background by the mdata svc so its ok if it takes
-# a little while to install all of the pkgs.
+set -o xtrace
 
 PATH=/opt/nodejs/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 
-role=ufds
-app_name=$role
+# This includes the fatal function and downloads and installs files.
+source /var/svc/setup.common
 
-cd /var/svc
-
-curl -o zoneconfig -s $CONFIG_assets_ip:/extra/$role/zoneconfig
-curl -o hn_config -s $CONFIG_assets_ip:/extra/$role/hn_config
-curl -o hn_generic -s $CONFIG_assets_ip:/extra/$role/hn_generic
-
-# Cookie to identify this as a SmartDC zone and its role
-mkdir -p /var/smartdc/ufds
-
-# We need some of the headnode config, but don't leave the files around
-. /var/svc/hn_config
-. /var/svc/hn_generic
-rm -f /var/svc/hn_config /var/svc/hn_generic
-# Load up the config values
-. /var/svc/zoneconfig
-
-# The user-script is downloaded and executed on every zone boot. We take
-# advantage of this to maintain the cached config values post-setup.
-# However, this zone currently has no local configuration to sync up.
-if [ -e /var/svc/setup_complete ]; then
-	exit 0
-fi
-
-# Setup the zone
-curl -o pkgsrc -s $CONFIG_assets_ip:/extra/$role/pkgsrc_2011q2_64
-curl -o fs.tar.bz2 -s $CONFIG_assets_ip:/extra/$role/fs.tar.bz2
-curl -o pkgsrc.tar -s $CONFIG_assets_ip:/extra/pkgsrc/pkgsrc_2011q2_64.tar
+eval $(cat /opt/smartdc/etc/zoneconfig)
 
 # Install UFDS
 mkdir -p /opt/smartdc/ufds/ssl
-mkdir /.stage
-echo "unpack fs.tar"
-(cd /.stage; bzcat /var/svc/fs.tar.bz2 | tar xbf 512 -)
-rm -f /var/svc/fs.tar.bz2
-echo "install root"
-(cd /.stage/root; tar cbf 512 - *) | (cd /opt/smartdc/ufds; tar xbf 512 -)
-rm -rf /.stage
 chown -R nobody:nobody /opt/smartdc/ufds
 
-# Install from local pkgsrc
-mkdir -p /var/svc/pkgs
-(cd /var/svc/pkgs && tar -xf /var/svc/pkgsrc.tar \
-      $(cat /var/svc/pkgsrc | sed -e "s/$/.tgz/" | xargs))
-rm -f /var/svc/pkgsrc.tar
-
-for i in `cat /var/svc/pkgsrc`
-do
-	echo "Installing $i"
-	pkg_info $i >/dev/null 2>&1 || pkg_add -f /var/svc/pkgs/$i
-done
-rm -rf /var/svc/pkgs
+# Install node/npm
+echo "Installing node and npm"
+cd /opt
+/usr/bin/gtar -j -m -xf /var/svc/nodejs-0.4.12.tar.bz2
+/usr/bin/chown -R nobody:nobody /opt/nodejs /opt/smartdc
+rm -f /var/svc/nodejs-0.4.12.tar.bz2
 
 echo "Creating log directory"
 mkdir -p /var/log/ufds
@@ -70,145 +30,7 @@ chown -R nobody:nobody /var/log/ufds
 echo "Generating SSL Certificate"
 /opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/ufds/ssl/key.pem -out /opt/smartdc/ufds/ssl/cert.pem -days 365
 
-echo "Creating SMF manifests"
-cat > /opt/smartdc/ufds/cfg/ufds_manifest.xml <<HERE
-<?xml version="1.0"?>
-<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
-<service_bundle type="manifest" name="ufds">
-  <service name="smartdc/site/ufds" type="service" version="7.0.0">
-
-    <create_default_instance enabled="true"/>
-    <single_instance/>
-
-    <dependency name="network" grouping="require_all" restart_on="error" type="service">
-      <service_fmri value="svc:/milestone/network:default"/>
-    </dependency>
-
-    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
-      <service_fmri value="svc:/system/filesystem/local"/>
-    </dependency>
-
-    <exec_method
-      type="method"
-      name="start"
-      exec="/opt/nodejs/bin/node /opt/smartdc/ufds/main.js -f /opt/smartdc/ufds/cfg/config.json&amp;"
-      timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/ufds">
-        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
-        <method_environment>
-          <envvar name="PATH" value="/opt/nodejs/bin:/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
-          <envvar name="LD_PRELOAD_32" value="/usr/lib/extendedFILE.so.1" />
-        </method_environment>
-      </method_context>
-    </exec_method>
-
-    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/ufds" />
-    </exec_method>
-
-    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/ufds" />
-    </exec_method>
-
-    <property_group name="startd" type="framework">
-      <propval name="ignore_error" type="astring" value="core,signal"/>
-    </property_group>
-
-    <property_group name="application" type="application">
-
-    </property_group>
-
-    <stability value="Stable"/>
-
-    <template>
-      <common_name>
-        <loctext xml:lang="C">UFDS daemon (ldapjs)</loctext>
-      </common_name>
-    </template>
-
-  </service>
-
-</service_bundle>
-HERE
-
-cat > /opt/smartdc/ufds/cfg/ufds_capi_manifest.xml <<HERE
-<?xml version="1.0"?>
-<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
-<service_bundle type="manifest" name="ufds-capi">
-  <service name="smartdc/site/ufds-capi" type="service" version="7.0.0">
-
-    <create_default_instance enabled="true"/>
-    <single_instance/>
-
-    <dependency name="network" grouping="require_all" restart_on="error" type="service">
-      <service_fmri value="svc:/milestone/network:default"/>
-    </dependency>
-
-    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
-      <service_fmri value="svc:/system/filesystem/local"/>
-    </dependency>
-
-    <exec_method
-      type="method"
-      name="start"
-      exec="/opt/nodejs/bin/node /opt/smartdc/ufds/capi.js -f /opt/smartdc/ufds/cfg/config.json&amp;"
-      timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/ufds">
-        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
-        <method_environment>
-          <envvar name="PATH" value="/opt/nodejs/bin:/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
-          <envvar name="LD_PRELOAD_32" value="/usr/lib/extendedFILE.so.1" />
-        </method_environment>
-      </method_context>
-    </exec_method>
-
-    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/ufds" />
-    </exec_method>
-
-    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
-      <method_context working_directory="/opt/smartdc/ufds" />
-    </exec_method>
-
-    <property_group name="startd" type="framework">
-      <propval name="ignore_error" type="astring" value="core,signal"/>
-    </property_group>
-
-    <property_group name="application" type="application">
-
-    </property_group>
-
-    <stability value="Stable"/>
-
-    <template>
-      <common_name>
-        <loctext xml:lang="C">UFDS CAPI Interface daemon (node)</loctext>
-      </common_name>
-    </template>
-
-  </service>
-
-</service_bundle>
-HERE
-
-# Update config file
-gsed -i -e "s/ROOTDN/$UFDS_LDAP_ROOT_DN/" /opt/smartdc/ufds/cfg/config.json.in
-gsed -i -e "s/ROOTPW/$UFDS_LDAP_ROOT_PW/" /opt/smartdc/ufds/cfg/config.json.in
-gsed -i -e "s/RIAK_IP/${RIAK_IP}/" /opt/smartdc/ufds/cfg/config.json.in
-gsed -i -e "s/RIAK_PORT/${RIAK_PORT}/" /opt/smartdc/ufds/cfg/config.json.in
-mv /opt/smartdc/ufds/cfg/config.json.in /opt/smartdc/ufds/cfg/config.json
-
-echo "Importing ufds_manifest.xml"
-/usr/sbin/svccfg import /opt/smartdc/ufds/cfg/ufds_manifest.xml
-
-echo "Importing ufds_capi_manifest.xml"
-/usr/sbin/svccfg import /opt/smartdc/ufds/cfg/ufds_capi_manifest.xml
-
-echo "Enabling service ufds"
-/usr/sbin/svcadm enable smartdc/site/ufds
-
-echo "Enabling service ufds-capi"
-/usr/sbin/svcadm enable smartdc/site/ufds-capi
+/opt/smartdc/bin/configure || fatal "Unable to configure zone."
 
 sleep 5
 echo "Loading bootstrap data"
@@ -242,7 +64,6 @@ objectclass: groupOfUniqueNames
 
 HERE
 
-
 LDAPTLS_REQCERT=allow /opt/local/bin/ldapadd -H ldaps://127.0.0.1:636 -x -D ${UFDS_LDAP_ROOT_DN} -w ${UFDS_LDAP_ROOT_PW} -f /tmp/.bootstrap.ldif
 if [ $? -ne 0 ] ; then
     echo "Failed to load bootstrap data, exiting"
@@ -252,7 +73,9 @@ if [ $? -ne 0 ] ; then
 fi
 
 rm -f /tmp/.bootstrap.ldif
-touch /var/svc/setup_complete
 
+touch /var/svc/setup_complete
 echo "setup done"
 (sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &
+
+exit 0
