HEAD-812 move paths to /usbkey/extra/<role> instead of /usbkey/extra/<uuid> to match 'refactored' zones.

diff --git a/zones/assets/user-script b/zones/assets/user-script
--- a/zones/assets/user-script
+++ b/zones/assets/user-script
@@ -4,8 +4,21 @@ set -o xtrace
 
 PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 
+# Only want to run this initial user-script once
+if [[ -f /var/svc/.ran-user-script ]]; then
+    echo "Initial user-script has already been run."
+    exit 0
+fi
+touch /var/svc/.ran-user-script
+
 zone_uuid=$(zonename)
-pkgsrc_lst=$(ls -1 /assets/extra/${zone_uuid}/pkgsrc_*)
+zone_role=$(mdata-get sdc:tags.smartdc_role)
+if [[ -z ${zone_role} ]]; then
+    echo "Unable to find zone role in metadata."
+    exit 1
+fi
+
+pkgsrc_lst=$(ls -1 /assets/extra/${zone_role}/pkgsrc_*)
 pkgsrc_tar=/assets/extra/pkgsrc/$(basename ${pkgsrc_lst}).tar
 
 # Install using local pkg repo
@@ -22,8 +35,8 @@ rm -rf /var/svc/pkgs
 
 mkdir -p /opt/smartdc/bin
 for file in configure configure.sh backup restore setup; do
-    if [[ -f /assets/extra/${zone_uuid}/${file} ]]; then
-        cp /assets/extra/${zone_uuid}/${file} /opt/smartdc/bin/${file}
+    if [[ -f /assets/extra/${zone_role}/${file} ]]; then
+        cp /assets/extra/${zone_role}/${file} /opt/smartdc/bin/${file}
     fi
 done
 chmod 755 /opt/smartdc/bin/*
diff --git a/zones/mapi/setup b/zones/mapi/setup
--- a/zones/mapi/setup
+++ b/zones/mapi/setup
@@ -62,8 +62,17 @@ function create_jill_account
 
 # ASSETS_IP is set by user-script before calling us.
 zone_uuid=$(zonename)
+zone_role=$(mdata-get sdc:tags.smartdc_role)
+
+if [[ -z ${zone_role} ]]; then
+    echo "Failed to find zone role in metadata."
+    exit 1
+fi
+
+echo "Configuring ${zone_role}..."
+
 curl -o /var/svc/mapi-data.zfs -s -S -f \
-    http://${ASSETS_IP}/extra/${zone_uuid}/mapi-data.zfs
+    http://${ASSETS_IP}/extra/${zone_role}/mapi-data.zfs
 if [[ -f /var/svc/mapi-data.zfs ]]; then
   zfs receive zones/${zone_uuid}/data/mapi-data < /var/svc/mapi-data.zfs
   zfs set mountpoint=/opt/smartdc/mapi-data zones/${zone_uuid}/data/mapi-data
@@ -128,28 +137,28 @@ rm /root/mapi-app-timestamp
 # Grab some extra data files from assets
 #
 curl -o /opt/smartdc/headnode-sysinfo.json -s -S -f \
-    http://${ASSETS_IP}/extra/${zone_uuid}/headnode-sysinfo.json
+    http://${ASSETS_IP}/extra/${zone_role}/headnode-sysinfo.json
 
 mkdir -p /opt/smartdc/joysetup
 curl -o /opt/smartdc/joysetup/joysetup.sh -s -S -f \
-    http://${ASSETS_IP}/extra/${zone_uuid}/joysetup.sh
+    http://${ASSETS_IP}/extra/${zone_role}/joysetup.sh
 
 mkdir -p /opt/smartdc/datasets
 for manifest in $(curl -s -S -f \
-    http://${ASSETS_IP}/extra/${zone_uuid}/datasets/ \
+    http://${ASSETS_IP}/extra/${zone_role}/datasets/ \
     | grep ".dsmanifest" | cut -d '"' -f2); do
 
     curl -o /opt/smartdc/datasets/${manifest} -s -S -f \
-        http://${ASSETS_IP}/extra/${zone_uuid}/datasets/${manifest}
+        http://${ASSETS_IP}/extra/${zone_role}/datasets/${manifest}
 done
 
 mkdir -p /opt/smartdc/agent-scripts
 for agents in $(curl -s -S -f \
-    http://${ASSETS_IP}/extra/${zone_uuid}/agents/ \
+    http://${ASSETS_IP}/extra/${zone_role}/agents/ \
     | grep "agents.*\.sh" | cut -d '"' -f2); do
 
     curl -o /opt/smartdc/agent-scripts/${agents} -s -S -f \
-        http://${ASSETS_IP}/extra/${zone_uuid}/agents/${agents}
+        http://${ASSETS_IP}/extra/${zone_role}/agents/${agents}
 done
 
 #
@@ -196,7 +205,7 @@ EOF
 
 # Pull down authorized_keys file if it's there
 curl -o /opt/smartdc/node.config/${ROOT_AUTHORIZED_KEYS_FILE} -s -S -f \
-    http://${ASSETS_IP}/extra/${zone_uuid}/config.inc/${ROOT_AUTHORIZED_KEYS_FILE}
+    http://${ASSETS_IP}/extra/${zone_role}/config.inc/${ROOT_AUTHORIZED_KEYS_FILE}
 
 # Generate the agents setup script:
 
