HEAD-1619 sdc-backup fails on redis zone
Switch redis backup/restore over to using the 'data' dataset to
which the redis zone has moved. Tested working with sdc-restore.

Also get 'sdc-backup' to show the output of the zone 'backup' scripts
(removing deadwood "All done!!!" echos). Fix a minor typo in
'sdc-backup' output for '-s'-skipped zones.

diff --git a/zones/redis/backup b/zones/redis/backup
--- a/zones/redis/backup
+++ b/zones/redis/backup
@@ -1,12 +1,11 @@
 #!/usr/bin/bash
 
-unset LD_LIBRARY_PATH
 PATH=/usr/bin:/usr/sbin
 export PATH
 
 if [[ $# != 2 ]]; then
-  echo "Usage: $0 <zone_name> <target_directory>"
-  exit 1
+    echo "Usage: $0 <zone_name> <target_directory>"
+    exit 1
 fi
 
 ZONE=$1
@@ -16,44 +15,35 @@ ROLE="redis"
 STAMP=$(date +'%F-%H-%M-%S-%Z')
 BACKUP_VERSION="${ROLE}-${STAMP}"
 
-ZONE_DATASET=$(zfs list -H -o name|grep "${ZONE}$")
-
-# We cannot backup if cannot find zone's dataset:
-if [[ -z $ZONE_DATASET ]]; then
-  echo "FATAL: Cannot find '${ROLE}' dataset"
-  exit 103
+if [[ ! -e "${TARGET_DIR}" ]]; then
+    mkdir -p ${TARGET_DIR}
 fi
 
-# Create dataset backup
-echo "==> Creating snapshot of '${ROLE}' dataset"
-zfs snapshot zones/${ZONE}@${BACKUP_VERSION} 2>&1
+DATA_DATASET=$(zfs list -H -o name|grep "${ZONE}/data$")
+if [[ -z $DATA_DATASET ]]; then
+    echo "FATAL: Cannot find '${ROLE}' data dataset"
+    exit 103
+fi
+
+echo "==> Creating snapshot of '${ZONE}/data' dataset"
+zfs snapshot zones/${ZONE}/data@${BACKUP_VERSION} 2>&1
 if [[ $? -gt 0 ]]; then
-    echo "FATAL: Unable to snapshot dataset"
-    exit 104
-fi
-
-# Just in case, create the backup directory:
-[[ ! -e "${TARGET_DIR}" ]] && mkdir -p ${TARGET_DIR}
-
-# Create backup directory for the zone stuff:
-echo "==> Creating backup directory '${TARGET_DIR}/${ROLE}'"
-mkdir -p "${TARGET_DIR}/${ROLE}"
-
-(cd /zones/$ZONE/.zfs/snapshot/${BACKUP_VERSION}/root/var/db; \
-    tar cbfE 512 ${TARGET_DIR}/${ROLE}/var_db.tar redis)
-if [[ $? -ne 0 ]]; then
-    echo "FATAL: Unable to backup database"
-    exit 105
-fi
-(cd /zones/$ZONE/.zfs/snapshot/${BACKUP_VERSION}/root/opt/redis/etc; \
-    tar cbf 512 ${TARGET_DIR}/${ROLE}/etc.tar *)
-if [[ $? -ne 0 ]]; then
-    echo "FATAL: Unable to backup configuration"
+    echo "FATAL: Unable to snapshot data dataset"
     exit 106
 fi
 
-echo "==> Removing temporary snapshot of '${ZONE}'"
-/usr/sbin/zfs destroy "zones/${ZONE}/${ROLE}@${BACKUP_VERSION}"
+echo "==> Creating backup directory '${TARGET_DIR}/${ROLE}'"
+mkdir -p "${TARGET_DIR}/${ROLE}"
 
-echo "All done!!!"
+echo "==> Saving data dataset"
+zfs send "zones/${ZONE}/data@${BACKUP_VERSION}" \
+    > "${TARGET_DIR}/${ROLE}/${ROLE}-data.zfs" 2>&1
+if [[ $? -gt 0 ]]; then
+    echo "Unable to zfs send data dataset"
+    exit 108
+fi
+
+echo "==> Removing temporary snapshot of '${ZONE}'"
+zfs destroy "zones/${ZONE}/data@${BACKUP_VERSION}"
+
 exit 0
diff --git a/zones/redis/restore b/zones/redis/restore
--- a/zones/redis/restore
+++ b/zones/redis/restore
@@ -1,45 +1,60 @@
 #!/usr/bin/bash
 
-unset LD_LIBRARY_PATH
 PATH=/usr/bin:/usr/sbin
 export PATH
 
 if [[ $# != 2 ]]; then
-  echo "Usage: $0 <zone_name> <target_directory>"
-  exit 1
+    echo "Usage: $0 <zone_name> <target_directory>"
+    exit 1
 fi
 
 ZONE=$1
 TARGET_DIR=$2
 ROLE="redis"
 
-if [[ ! -d "${TARGET_DIR}" || ! -d ${TARGET_DIR}/${ROLE} ]]; then
-    echo "Missing backup directory"
-    exit 107
+# Don't want redis running while swapping its data.
+svcadm disable redis
+
+# Destroy previous data dataset.
+DATA_DATASET=$(zfs list -H -o name|grep "${ZONE}/data$")
+if [[ -z "${DATA_DATASET}" ]]; then
+    echo "FATAL: Missing '${DATA_DATASET}' dataset"
+    exit 105
+fi
+echo "==> Destroying dataset '${DATA_DATASET}'"
+zfs destroy -r "${DATA_DATASET}"
+if [[ $? -gt 0 ]]; then
+    echo "FATAL: Unable to zfs destroy '${DATA_DATASET}' dataset"
+    exit 106
 fi
 
-if [[ ! -f ${TARGET_DIR}/${ROLE}/etc.tar ]]; then
-    echo "Incomplete backup directory"
-    exit 109
+echo "==> Receiving '${TARGET_DIR}/${ROLE}/${ROLE}-data.zfs'"
+zfs receive -v "${DATA_DATASET}" < "${TARGET_DIR}/${ROLE}/${ROLE}-data.zfs"
+if [[ $? -gt 0 ]]; then
+    echo "FATAL: Unable to zfs receive data dataset"
+    exit 108
 fi
 
-if [[ ! -f ${TARGET_DIR}/${ROLE}/var_db.tar ]]; then
-    echo "Incomplete backup directory"
-    exit 110
-fi
+svcadm enable redis
 
-echo "==> Restoring $ROLE backup"
-(cd /zones/$ZONE/root/var/db; tar xbfE 512 ${TARGET_DIR}/${ROLE}/var_db.tar)
-if [[ $? -ne 0 ]]; then
-    echo "Error: restoring database"
-    exit 111
-fi
-(cd /zones/$ZONE/root/opt/redis/etc; \
-    tar xbf 512 ${TARGET_DIR}/${ROLE}/etc.tar)
-if [[ $? -ne 0 ]]; then
-    echo "Error: restoring configuration"
-    exit 112
-fi
 
-echo "All done!!!"
+# Reboot the zone to set mountpoint for the new dataset properly. Then
+# double check.
+echo "==> Booting '${ZONE}' zone"
+/usr/sbin/zoneadm -z ${ZONE} boot
+if [[ "$(zfs get -H -o value mountpoint ${DATA_DATASET})" != "/data" ]]; then
+    echo "==> Setting mountpoint for dataset '${DATA_DATASET}'"
+    zlogin ${ZONE} /usr/sbin/zfs set mountpoint=/data "${DATA_DATASET}"
+    if [[ $? -gt 0 ]]; then
+        echo "FATAL: Unable to set mountpoint for data dataset into '${ZONE}' zone"
+        exit 112
+    fi
+fi
+echo "==> Waiting for 10 seconds while the zone services are running"
+sleep 10
+
+
+echo "==> Halting '${ZONE}' zone"
+/usr/sbin/zoneadm -z ${ZONE} halt
+
 exit 0
