MON-153 email notifications not getting through (no postfix service)

diff --git a/zones/amon/setup b/zones/amon/setup
--- a/zones/amon/setup
+++ b/zones/amon/setup
@@ -3,7 +3,9 @@
 # Copyright (c) 2011, Joyent Inc. All rights reserved.
 #
 
+export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 set -o xtrace
+#set -o errexit
 
 PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 
@@ -22,7 +24,8 @@ echo "export PATH=\$PATH:/opt/smartdc/$role/build/node/bin:/opt/smartdc/$role/no
 /opt/smartdc/bin/configure || fatal "unable to configure"
 
 # Amon master needs postfix to send email notifications.
-/usr/sbin/svcadm enable postfix
+/usr/sbin/svccfg import /opt/local/share/smf/postfix/manifest.xml || fatal "unable to import postfix SMF manifest"
+/usr/sbin/svcadm enable postfix || fatal "unable to enable postfix"
 
 touch /var/svc/setup_complete
 echo "setup done"
