MORAY-160 multi-process moray

diff --git a/zones/moray/configure b/zones/moray/configure
--- a/zones/moray/configure
+++ b/zones/moray/configure
@@ -22,6 +22,7 @@ role=moray
 
 
 ZONE_UUID=`/usr/bin/zonename`
+SVC_ROOT='/opt/smartdc/moray'
 
 
 echo "Updating /etc/rsyslog.conf"
@@ -66,6 +67,53 @@ HERE
 svcadm restart system-log
 [[ $? -eq 0 ]] || fatal "Unable to restart rsyslog"
 
+# setup haproxy
+function manta_setup_moray {
+    local moray_instances=4
+
+    #Build the list of ports.  That'll be used for everything else.
+    local ports
+    for (( i=1; i<=$moray_instances; i++ )); do
+        ports[$i]=`expr 2020 + $i`
+    done
+
+    #To preserve whitespace in echo commands...
+    IFS='%'
+
+    #haproxy
+    for port in "${ports[@]}"; do
+        hainstances="$hainstances        server moray-$port 127.0.0.1:$port check inter 10s slowstart 10s error-limit 3 on-error mark-down\n"
+    done
+
+    sed -e "s#@@MORAY_INSTANCES@@#$hainstances#g" \
+        $SVC_ROOT/etc/haproxy.cfg.in > $SVC_ROOT/etc/haproxy.cfg || \
+        fatal "could not process $src to $dest"
+
+    svccfg import $SVC_ROOT/smf/manifests/haproxy.xml || \
+        fatal "unable to import haproxy"
+    svcadm enable "manta/haproxy" || fatal "unable to start haproxy"
+
+    #moray instances
+    local moray_xml_in=$SVC_ROOT/smf/manifests/moray.xml.in
+    for port in "${ports[@]}"; do
+        local moray_instance="moray-$port"
+        local moray_xml_out=$SVC_ROOT/smf/manifests/moray-$port.xml
+        sed -e "s#@@MORAY_PORT@@#$port#g" \
+            -e "s#@@MORAY_INSTANCE_NAME@@#$moray_instance#g" \
+            $moray_xml_in  > $moray_xml_out || \
+            fatal "could not process $moray_xml_in to $moray_xml_out"
+
+        svccfg import $moray_xml_out || \
+            fatal "unable to import $moray_instance: $moray_xml_out"
+        svcadm enable "$moray_instance" || \
+            fatal "unable to start $moray_instance"
+    done
+
+    unset IFS
+}
+
+manta_setup_moray
+
 # echo "Updating config file"
 # CFG_FILE_IN=/opt/smartdc/$role/etc/config.json.in
 # CFG_FILE=/opt/smartdc/$role/etc/config.json
@@ -74,12 +122,12 @@ svcadm restart system-log
 # cp $CFG_FILE_IN $CFG_FILE
 # gsed -i -e "s|ZK_IP|$BINDER_MAIN_ADMIN_IP|" $CFG_FILE
 
-echo "Importing SMF Manifests"
-sed -e "s#@@MORAY_PORT@@#2020#g" \
-    -e "s#@@MORAY_INSTANCE_NAME@@#default#g" \
-    /opt/smartdc/$role/smf/manifests/$role.xml.in  \
-    > /opt/smartdc/$role/smf/manifests/$role.xml || \
-    fatal "could not process /opt/smartdc/$role/smf/manifests/$role.xml.in"
-$(/usr/sbin/svccfg import /opt/smartdc/$role/smf/manifests/$role.xml)
+#echo "Importing SMF Manifests"
+#sed -e "s#@@MORAY_PORT@@#2020#g" \
+    #-e "s#@@MORAY_INSTANCE_NAME@@#default#g" \
+    #/opt/smartdc/$role/smf/manifests/$role.xml.in  \
+    #> /opt/smartdc/$role/smf/manifests/$role.xml || \
+    #fatal "could not process /opt/smartdc/$role/smf/manifests/$role.xml.in"
+#$(/usr/sbin/svccfg import /opt/smartdc/$role/smf/manifests/$role.xml)
 
 exit 0
