MANTA-908: Move moray DB creation from zone configure to setup.

diff --git a/zones/moray/setup b/zones/moray/setup
--- a/zones/moray/setup
+++ b/zones/moray/setup
@@ -13,6 +13,7 @@ role=moray
 # This includes the fatal function and downloads and installs files.
 source /var/svc/setup.common
 
+eval $(cat /opt/smartdc/etc/zoneconfig)
 
 # Cookie to identify this as a SmartDC zone and its role
 mkdir -p /var/smartdc/$role
@@ -42,6 +43,59 @@ logadm -w moray -C 48 -c -p 1h \
 
 echo '0 * * * * /usr/sbin/logadm' > /etc/cron.d/logadm
 crontab /etc/cron.d/logadm
+
+
+MANATEE_MAIN_ADMIN_IP=$(echo "${MANATEE_ADMIN_IPS}" | cut -d',' -f1)
+
+# Try to connect to manatee PostgreSQL instance. If we can connect, create the
+# moray db when required. If we cannot connect after 10 retries, fail and exit.
+#
+# FIXME: Actually, we're manually overriding manatee's PG Password and setting
+# the PG user to the default one. These should be configuration values:
+POSTGRES_HOST=$MANATEE_MAIN_ADMIN_IP
+POSTGRES_PW=''
+for i in 0 1 2 3 4 5 6 7 8 9
+do
+    if ! PGPASSWORD=${POSTGRES_PW} /opt/local/bin/psql -U ${POSTGRES_USER} \
+        -h ${POSTGRES_HOST} -c "\l" 2>/dev/null; then
+        sleep 5
+        if [[ "$i" == "9" ]]; then
+            echo "Connecting to manatee PostgreSQL failed. Exiting."
+            exit 1
+        else
+            continue
+        fi
+    else
+      if [[ -z $(PGPASSWORD=${POSTGRES_PW} /opt/local/bin/psql \
+          -U ${POSTGRES_USER} \
+          -h ${POSTGRES_HOST} -c "\l"|grep $role) ]]; then
+            echo "Creating $role database"
+            PGPASSWORD=${POSTGRES_PW} /opt/local/bin/createdb \
+            -U ${POSTGRES_USER} \
+            -h ${POSTGRES_HOST} $role
+          if [[ -z $(PGPASSWORD=${POSTGRES_PW} /opt/local/bin/psql \
+                -U ${POSTGRES_USER} \
+                -h ${POSTGRES_HOST} ${role} -c "\dt"|grep buckets_config) ]]; then
+              echo "Creating table buckets_config"
+              PGPASSWORD=${POSTGRES_PW} /opt/local/bin/psql \
+                -U ${POSTGRES_USER} \
+                -h ${POSTGRES_HOST} $role -c "CREATE TABLE buckets_config (
+                    name text PRIMARY KEY,
+                    index text NOT NULL,
+                    pre text NOT NULL,
+                    post text NOT NULL,
+                    options text,
+                    mtime timestamp without time zone DEFAULT now() NOT NULL
+                );"
+              break
+          else
+              break
+          fi
+      else
+          break
+      fi
+    fi
+done
 
 
 # Configure zone
