HEAD-663 backup/restore improvements from JPC meltdown

diff --git a/zones/cloudapi/backup b/zones/cloudapi/backup
--- a/zones/cloudapi/backup
+++ b/zones/cloudapi/backup
@@ -3,9 +3,6 @@
 # Copyright (c) 2011 Joyent Inc., All rights reserved.
 #
 
-set -o errexit
-#set -o xtrace
-
 if [[ $# != 2 ]]; then
     echo "Usage: $0 <zone_name> <target_directory>"
     exit 1
@@ -13,27 +10,18 @@ fi
 
 ZONE=$1
 TARGET_DIR=$2
+CFG_FILE=/zones/cloudapi/root/opt/smartdc/cloudapi/cfg/config.json
 
-TIMESTAMP=`TZ=UTC date "+%Y%m%dT%H%M%SZ"`
-BACKUP_SNAP="zones/${ZONE}@backup-${TIMESTAMP}"
-
-# Just in case, create the backup directory:
-if [[ ! -e "${TARGET_DIR}" ]]; then
-    mkdir -p ${TARGET_DIR}
+if [[ ! -d "${TARGET_DIR}" ]]; then
+    echo "Invalid directory: '${TARGET_DIR}'"
+    exit 1
 fi
 
-# Snapshot the zone
-echo "==> Creating temporary snapshot of '${ZONE}' dataset"
-/usr/sbin/zfs snapshot ${BACKUP_SNAP}
+# Create the backup directory:
+mkdir -p ${TARGET_DIR}/${ZONE}
 
-echo "==> Copying snapshot of '${ZONE}'"
-/usr/sbin/zfs send ${BACKUP_SNAP} > ${TARGET_DIR}/${ZONE}.zfs
+echo "==> Saving config file for zone '${ZONE}'"
+[ -f $CFG_FILE ] && cp $CFG_FILE ${TARGET_DIR}/${ZONE}
 
-echo "==> Removing temporary snapshot of '${ZONE}'"
-/usr/sbin/zfs destroy ${BACKUP_SNAP}
-
-echo "==> Writing timestamp"
-echo "${TIMESTAMP}" > ${TARGET_DIR}/timestamp
-
-echo "==> Done"
+echo "==> Done!"
 exit 0
diff --git a/zones/portal/restore b/zones/portal/restore
--- a/zones/portal/restore
+++ b/zones/portal/restore
@@ -1,1 +1,25 @@
-../../common/restore.simple
+#!/usr/bin/bash
+#
+# Copyright (c) 2011 Joyent Inc., All rights reserved.
+#
+
+if [[ $# != 2 ]]; then
+    echo "Usage: $0 <zone_name> <src_directory>"
+    exit 1
+fi
+
+ZONE=$1
+SRC_DIR=$2
+CFG_FILE=/zones/$ZONE/root/opt/smartdc/portal/cfg/capi.json
+
+# Older backups may not have had this zone
+if [[ -d "${SRC_DIR}/${ZONE}" && -f "${SRC_DIR}/${ZONE}/capi.json" ]]; then
+	echo "==> Restoring config file for zone '${ZONE}'"
+	cp ${SRC_DIR}/${ZONE}/capi.json $CFG_FILE
+
+else
+	echo "Warning, older backup; missing config file for $ZONE"
+fi
+
+echo "==> Done"
+exit 0
