HEAD-1187: Added node and node_modules to the node app zones root PATH

diff --git a/zones/cloudapi/setup b/zones/cloudapi/setup
--- a/zones/cloudapi/setup
+++ b/zones/cloudapi/setup
@@ -7,22 +7,24 @@ set -o xtrace
 
 PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 
+role=cloudapi
+
 # This includes the fatal function and downloads and installs files.
 source /var/svc/setup.common
 
 # Cookie to identify this as a SmartDC zone and its role
-mkdir -p /var/smartdc/cloudapi
-mkdir -p /opt/smartdc/cloudapi/ssl
+mkdir -p /var/smartdc/$role
+mkdir -p /opt/smartdc/$role/ssl
 
 echo "Installing local node.js"
-mkdir -p /opt/smartdc/cloudapi/cfg
+mkdir -p /opt/smartdc/$role/cfg
 cd -
 /usr/bin/chown -R root:root /opt/smartdc
 
 echo "Generating SSL Certificate"
 /opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 \
-    -keyout /opt/smartdc/cloudapi/ssl/key.pem \
-    -out /opt/smartdc/cloudapi/ssl/cert.pem -days 365
+    -keyout /opt/smartdc/$role/ssl/key.pem \
+    -out /opt/smartdc/$role/ssl/cert.pem -days 365
 
 # Setup HAProxy user/group
 /usr/sbin/groupadd haproxy
@@ -31,10 +33,10 @@ echo "Generating SSL Certificate"
 
 # Add build/node/bin and node_modules/.bin to PATH
 echo "" >>/root/.bashrc
-echo "export PATH=\$PATH:/opt/smartdc/cloudapi/build/node/bin:/opt/smartdc/cloudapi/node_modules/.bin" >>/root/.bashrc
+echo "export PATH=\$PATH:/opt/smartdc/$role/build/node/bin:/opt/smartdc/$role/node_modules/.bin" >>/root/.bashrc
 
 # do configuration now.
-/opt/smartdc/bin/configure || fatal "Unable to configure cloudapi zone"
+/opt/smartdc/bin/configure || fatal "Unable to configure $role zone"
 
 touch /var/svc/setup_complete
 echo "setup done"
