Revert "[PUBAPI-685] Multiple CloudAPI instances + HAproxy"
This reverts commit 3fca02cea5b4fad8f1c76074e30444a9e35c47cd.

Rolling back CloudAPI HAproxy until [PUBAPI-685] subtasks are completed

diff --git a/zones/cloudapi/setup b/zones/cloudapi/setup
--- a/zones/cloudapi/setup
+++ b/zones/cloudapi/setup
@@ -11,8 +11,6 @@ PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
 role=cloudapi
 # Local SAPI manifests:
 CONFIG_AGENT_LOCAL_MANIFESTS_DIRS=/opt/smartdc/$role
-# This is just shortest
-SVC_ROOT=/opt/smartdc/$role
 # This includes the fatal function and downloads and installs files.
 source /var/svc/setup.common
 
@@ -31,59 +29,15 @@ echo "Generating SSL Certificate"
 echo "" >>/root/.profile
 echo "export PATH=\$PATH:/opt/smartdc/$role/build/node/bin:/opt/smartdc/$role/node_modules/.bin" >>/root/.profile
 
-# setup haproxy
-function setup_cloudapi {
-    local cloudapi_instances=4
-
-    #Build the list of ports.  That'll be used for everything else.
-    local ports
-    for (( i=1; i<=$cloudapi_instances; i++ )); do
-        ports[$i]=`expr 8080 + $i`
-    done
-
-    #To preserve whitespace in echo commands...
-    IFS='%'
-
-    #haproxy
-    for port in "${ports[@]}"; do
-        hainstances="$hainstances        server cloudapi-$port 127.0.0.1:$port check inter 10s slowstart 10s error-limit 3 on-error mark-down\n"
-    done
-
-    sed -e "s#@@CLOUDAPI_INSTANCES@@#$hainstances#g" \
-        $SVC_ROOT/etc/haproxy.cfg.in > $SVC_ROOT/etc/haproxy.cfg || \
-        fatal "could not process $src to $dest"
-
-    svccfg import $SVC_ROOT/smf/manifests/haproxy.xml || \
-        fatal "unable to import haproxy"
-    svcadm enable "cloudapi/haproxy" || fatal "unable to start haproxy"
-
-    #cloudapi instances
-    local cloudapi_xml_in=$SVC_ROOT/smf/manifests/cloudapi.xml.in
-    for port in "${ports[@]}"; do
-        local cloudapi_instance="cloudapi-$port"
-        local cloudapi_xml_out=$SVC_ROOT/smf/manifests/cloudapi-$port.xml
-        sed -e "s#@@CLOUDAPI_PORT@@#$port#g" \
-            -e "s#@@CLOUDAPI_INSTANCE_NAME@@#$cloudapi_instance#g" \
-            -e "s/@@PREFIX@@/\/opt\/smartdc\/cloudapi/g" \
-            $cloudapi_xml_in  > $cloudapi_xml_out || \
-            fatal "could not process $cloudapi_xml_in to $cloudapi_xml_out"
-
-        svccfg import $cloudapi_xml_out || \
-            fatal "unable to import $cloudapi_instance: $cloudapi_xml_out"
-        svcadm enable "$cloudapi_instance" || \
-            fatal "unable to start $cloudapi_instance"
-        echo "Adding log rotation"
-        logadm -w $cloudapi_instance -C 48 -s 100m -p 1h \
-            /var/svc/log/smartdc-application-cloudapi:$cloudapi_instance.log
-    done
-
-    unset IFS
-}
-
-setup_cloudapi
+# do configuration now.
+/opt/smartdc/bin/configure || fatal "Unable to configure $role zone"
 
 # Install Amon monitor and probes for CloudAPI
 TRACE=1 /opt/smartdc/cloudapi/bin/cloudapi-amon-install
+
+echo "Adding log rotation"
+logadm -w cloudapi -C 48 -s 100m -p 1h \
+    /var/svc/log/smartdc-application-cloudapi:default.log
 
 touch /var/svc/setup_complete
 echo "setup done"
