IMGAPI-283: Redirect echo error to stderr

diff --git a/tools/sdc-imgadm b/tools/sdc-imgadm
--- a/tools/sdc-imgadm
+++ b/tools/sdc-imgadm
@@ -8,7 +8,7 @@
 ufds_admin_uuid=$(bash /lib/sdc/config.sh -json | json ufds_admin_uuid)
 sdc_zone=$(vmadm list -H -o tags.smartdc_role,uuid,create_timestamp -s create_timestamp owner_uuid=$ufds_admin_uuid | grep '^sdc\>' | tail -1 | awk '{print $2}')
 if [[ -z "${sdc_zone}" ]]; then
-    echo "error: $(basename $0): unable to find a 'sdc' core zone on this node"
+    echo "error: $(basename $0): unable to find a 'sdc' core zone on this node" >&2
     exit 1
 fi
 exec /zones/$sdc_zone/root/opt/smartdc/sdc/bin/$(basename $0) "$@"
