BILLING-317 - updated backup/restore scripts for usageapi to work with delegated dataset.

diff --git a/zones/usageapi/backup b/zones/usageapi/backup
--- a/zones/usageapi/backup
+++ b/zones/usageapi/backup
@@ -17,6 +17,7 @@ STAMP=$(date +'%F-%H-%M-%S-%Z')
 BACKUP_VERSION="${ROLE}-${STAMP}"
 
 ZONE_DATASET=$(zfs list -H -o name|grep "${ZONE}$")
+DATA_DATASET=$(zfs list -H -o name|grep "${ZONE}/data$")
 
 # We cannot backup if cannot find zone's dataset:
 if [[ -z $ZONE_DATASET ]]; then
@@ -24,36 +25,58 @@ if [[ -z $ZONE_DATASET ]]; then
   exit 103
 fi
 
-# Create dataset backup
-echo "==> Creating snapshot of '${ROLE}' dataset"
-zfs snapshot zones/${ZONE}@${BACKUP_VERSION} 2>&1
-if [[ $? -gt 0 ]]; then
-    echo "FATAL: Unable to snapshot dataset"
-    exit 104
+# We cannot backup if cannot find data dataset:
+if [[ -z $DATA_DATASET ]]; then
+  echo "FATAL: Cannot find '${ROLE}' data dataset"
+  exit 104
 fi
 
-# Just in case, create the backup directory:
-[[ ! -e "${TARGET_DIR}" ]] && mkdir -p ${TARGET_DIR}
+# Create zone dataset backup
+echo "==> Creating snapshot of '${ZONE}' dataset"
+zfs snapshot "zones/${ZONE}@${BACKUP_VERSION}" 2>&1
+if [[ $? -gt 0 ]]; then
+    echo "FATAL: Unable to snapshot dataset"
+    exit 105
+fi
+
+# Create data dataset backup
+echo "==> Creating snapshot of '${ZONE}/data' dataset"
+zfs snapshot "zones/${ZONE}/data@${BACKUP_VERSION}" 2>&1
+if [[ $? -gt 0 ]]; then
+  echo "FATAL: Unable to snapshot data dataset"
+  exit 106
+fi
 
 # Create backup directory for the zone stuff:
 echo "==> Creating backup directory '${TARGET_DIR}/${ROLE}'"
+[[ ! -e "${TARGET_DIR}" ]] && mkdir -p "${TARGET_DIR}"
 mkdir -p "${TARGET_DIR}/${ROLE}"
 
-(cd /zones/$ZONE/.zfs/snapshot/${BACKUP_VERSION}/root/var; \
-    tar cbfzE 512 ${TARGET_DIR}/${ROLE}/var.tar.gz pgsql)
-if [[ $? -ne 0 ]]; then
-    echo "FATAL: Unable to backup database"
-    exit 105
-fi
-(cd /zones/$ZONE/.zfs/snapshot/${BACKUP_VERSION}/root/opt/smartdc/usageapi/config; \
-    tar cbzfE 512 ${TARGET_DIR}/${ROLE}/config.tar.gz *)
-if [[ $? -ne 0 ]]; then
-    echo "FATAL: Unable to backup configuration"
-    exit 106
+echo "==> Saving data dataset"
+zfs send "zones/${ZONE}/data@${BACKUP_VERSION}" \
+    > "${TARGET_DIR}/${ROLE}/data.zfs" 2>&1
+if [[ $? -gt 0 ]]; then
+  echo "Unable to zfs send data dataset"
+  exit 107
 fi
 
-echo "==> Removing temporary snapshot of '${ZONE}'"
-/usr/sbin/zfs destroy "zones/${ZONE}/${ROLE}@${BACKUP_VERSION}"
+echo "==> Removing temporary data snapshot of '${ZONE}'"
+/usr/sbin/zfs destroy "zones/${ZONE}/data@${BACKUP_VERSION}"
+
+echo "==> Saving configs"
+(cd "/zones/${ZONE}/.zfs/snapshot/${BACKUP_VERSION}/root/opt/smartdc/usageapi"; \
+    tar cbzfE 512 "${TARGET_DIR}/${ROLE}/config.tar.gz" config/*)
+if [[ $? -ne 0 ]]; then
+  echo "FATAL: Unable to backup configuration"
+  exit 108
+fi
+
+echo "==> Saving logs"
+(cd "/zones/${ZONE}/.zfs/snapshot/${BACKUP_VERSION}/root/var/svc"; \
+    tar cbzfE 512 "${TARGET_DIR}/${ROLE}/logs.tar.gz" log/*usageapi*)
+
+echo "==> Removing temporary zone snapshot of '${ZONE}'"
+/usr/sbin/zfs destroy "zones/${ZONE}@${BACKUP_VERSION}"
 
 echo "All done!!!"
 exit 0
diff --git a/zones/usageapi/restore b/zones/usageapi/restore
--- a/zones/usageapi/restore
+++ b/zones/usageapi/restore
@@ -13,33 +13,64 @@ ZONE=$1
 TARGET_DIR=$2
 ROLE="usageapi"
 
-if [[ ! -d "${TARGET_DIR}" || ! -d ${TARGET_DIR}/${ROLE} ]]; then
-    echo "Missing backup directory"
-    exit 107
+# Get existing data dataset.
+DATA_DATASET=$(zfs list -H -o name|grep "${ZONE}/data$")
+
+# Destroy previous dataset.
+if [[ -z "${DATA_DATASET}" ]]; then
+  echo "FATAL: Missing '${DATA_DATASET}' dataset"
+  exit 105
 fi
 
-if [[ ! -f ${TARGET_DIR}/${ROLE}/config.tar.gz ]]; then
-    echo "Incomplete backup directory"
-    exit 109
+echo "==> Destroying dataset '${DATA_DATASET}'"
+zfs destroy -r "${DATA_DATASET}"
+if [[ $? -gt 0 ]]; then
+  echo "FATAL: Unable to zfs destroy '${DATA_DATASET}' dataset"
+  exit 106
 fi
 
-if [[ ! -f ${TARGET_DIR}/${ROLE}/var.tar.gz ]]; then
-    echo "Incomplete backup directory"
-    exit 110
+# ZFS receive the dataset from the backup:
+echo "==> Receiving '${TARGET_DIR}/${ROLE}/data.zfs'"
+zfs receive -v "${DATA_DATASET}" < "${TARGET_DIR}/${ROLE}/data.zfs"
+if [[ $? -gt 0 ]]; then
+  echo "FATAL: Unable to zfs receive data dataset"
+  exit 108
 fi
 
-echo "==> Restoring $ROLE backup"
-(cd /zones/$ZONE/root/var; tar xzbfE 512 ${TARGET_DIR}/${ROLE}/var.tar.gz)
-if [[ $? -ne 0 ]]; then
-    echo "Error: restoring database"
-    exit 111
-fi
-(cd /zones/$ZONE/root/opt/smartdc/usageapi/config; \
-    tar xzbfE 512 ${TARGET_DIR}/${ROLE}/config.tar.gz)
-if [[ $? -ne 0 ]]; then
-    echo "Error: restoring configuration"
-    exit 112
+echo "==> Restoring configs"
+gzcat "${TARGET_DIR}/${ROLE}/config.tar.gz" | \
+  (cd "/zones/${ZONE}/root/opt/smartdc/usageapi"; tar xbf 512 -)
+if [[ $? -gt 0 ]]; then
+  echo "FATAL: Unable to restore configs"
+  exit 109
 fi
 
-echo "All done!!!"
+echo "==> Restoring logs"
+gzcat "${TARGET_DIR}/${ROLE}/logs.tar.gz" | \
+  (cd "/zones/${ZONE}/root/var/svc"; tar xbf 512 -)
+
+# Double check mountpoint for backup dataset:
+if [[ "$(zfs get -H -o value mountpoint ${DATA_DATASET})" != \
+    "/zones/${ZONE}/data"  ]]; then
+
+    # We need to boot the zone in order to be able to set mountpoint for the
+    # delegated dataset properly:
+    echo "==> Booting '${ZONE}' zone"
+    /usr/sbin/zoneadm -z "${ZONE}" boot
+
+    echo "==> Setting mountpoint for dataset '${DATA_DATASET}'"
+    zlogin ${ZONE} /usr/sbin/zfs set mountpoint="/zones/${ZONE}/data" \
+       "${DATA_DATASET}"
+    if [[ $? -gt 0 ]]; then
+        echo "FATAL: Unable to set mountpoint for data dataset into '${ZONE}' zone"
+        /usr/sbin/zoneadm -z "${ZONE}" halt
+        exit 112
+    fi
+
+    echo "==> Halting '${ZONE}' zone"
+    /usr/sbin/zoneadm -z "${ZONE}" halt
+fi
+
+echo "==> All done!!!"
 exit 0
+
