BILLING-287 - backup/restore for usageapi now handles the Postgres database in that zone as well.

diff --git a/zones/usageapi/backup b/zones/usageapi/backup
--- a/zones/usageapi/backup
+++ b/zones/usageapi/backup
@@ -1,31 +1,59 @@
 #!/usr/bin/bash
-#
-# Copyright (c) 2011 Joyent Inc., All rights reserved.
-#
 
+unset LD_LIBRARY_PATH
 PATH=/usr/bin:/usr/sbin
 export PATH
 
 if [[ $# != 2 ]]; then
-    echo "Usage: $0 <zone_name> <target_directory>"
-    exit 1
+  echo "Usage: $0 <zone_name> <target_directory>"
+  exit 1
 fi
 
-ROLE=usageapi
-UUID=$1
+ZONE=$1
 TARGET_DIR=$2
-CFG_FILE=/zones/$UUID/root/opt/smartdc/usageapi/config/config.json
+ROLE="usageapi"
 
-if [[ ! -d "${TARGET_DIR}" ]]; then
-    echo "Invalid directory: '${TARGET_DIR}'"
-    exit 1
+STAMP=$(date +'%F-%H-%M-%S-%Z')
+BACKUP_VERSION="${ROLE}-${STAMP}"
+
+ZONE_DATASET=$(zfs list -H -o name|grep "${ZONE}$")
+
+# We cannot backup if cannot find zone's dataset:
+if [[ -z $ZONE_DATASET ]]; then
+  echo "FATAL: Cannot find '${ROLE}' dataset"
+  exit 103
 fi
 
-# Create the backup directory:
-mkdir -p ${TARGET_DIR}/${ROLE}
+# Create dataset backup
+echo "==> Creating snapshot of '${ROLE}' dataset"
+zfs snapshot zones/${ZONE}@${BACKUP_VERSION} 2>&1
+if [[ $? -gt 0 ]]; then
+    echo "FATAL: Unable to snapshot dataset"
+    exit 104
+fi
 
-echo "==> Saving config file for zone '${ROLE}'"
-[ -f $CFG_FILE ] && cp $CFG_FILE ${TARGET_DIR}/${ROLE}
+# Just in case, create the backup directory:
+[[ ! -e "${TARGET_DIR}" ]] && mkdir -p ${TARGET_DIR}
 
-echo "==> Done!"
+# Create backup directory for the zone stuff:
+echo "==> Creating backup directory '${TARGET_DIR}/${ROLE}'"
+mkdir -p "${TARGET_DIR}/${ROLE}"
+
+(cd /zones/$ZONE/.zfs/snapshot/${BACKUP_VERSION}/root/var; \
+    tar cbfzE 512 ${TARGET_DIR}/${ROLE}/var.tar.gz pgsql)
+if [[ $? -ne 0 ]]; then
+    echo "FATAL: Unable to backup database"
+    exit 105
+fi
+(cd /zones/$ZONE/.zfs/snapshot/${BACKUP_VERSION}/root/opt/smartdc/usageapi/config; \
+    tar cbzfE 512 ${TARGET_DIR}/${ROLE}/config.tar.gz *)
+if [[ $? -ne 0 ]]; then
+    echo "FATAL: Unable to backup configuration"
+    exit 106
+fi
+
+echo "==> Removing temporary snapshot of '${ZONE}'"
+/usr/sbin/zfs destroy "zones/${ZONE}/${ROLE}@${BACKUP_VERSION}"
+
+echo "All done!!!"
 exit 0
diff --git a/zones/usageapi/restore b/zones/usageapi/restore
--- a/zones/usageapi/restore
+++ b/zones/usageapi/restore
@@ -1,29 +1,45 @@
 #!/usr/bin/bash
-#
-# Copyright (c) 2011 Joyent Inc., All rights reserved.
-#
 
+unset LD_LIBRARY_PATH
 PATH=/usr/bin:/usr/sbin
 export PATH
 
 if [[ $# != 2 ]]; then
-    echo "Usage: $0 <zone_name> <src_directory>"
-    exit 1
+  echo "Usage: $0 <zone_name> <target_directory>"
+  exit 1
 fi
 
-ROLE=usageapi
-UUID=$1
-SRC_DIR=$2
-CFG_FILE=/zones/$UUID/root/opt/smartdc/usageapi/config/config.json
+ZONE=$1
+TARGET_DIR=$2
+ROLE="usageapi"
 
-# Older backups may not have had this zone
-if [[ -d "${SRC_DIR}/${ROLE}" && -f "${SRC_DIR}/${ROLE}/config.json" ]]; then
-	echo "==> Restoring config file for zone '${ROLE}'"
-	cp ${SRC_DIR}/${ROLE}/config.json $CFG_FILE
-
-else
-	echo "Warning, older backup; missing config file for $ROLE"
+if [[ ! -d "${TARGET_DIR}" || ! -d ${TARGET_DIR}/${ROLE} ]]; then
+    echo "Missing backup directory"
+    exit 107
 fi
 
-echo "==> Done"
+if [[ ! -f ${TARGET_DIR}/${ROLE}/config.tar.gz ]]; then
+    echo "Incomplete backup directory"
+    exit 109
+fi
+
+if [[ ! -f ${TARGET_DIR}/${ROLE}/var.tar.gz ]]; then
+    echo "Incomplete backup directory"
+    exit 110
+fi
+
+echo "==> Restoring $ROLE backup"
+(cd /zones/$ZONE/root/var; tar xzbfE 512 ${TARGET_DIR}/${ROLE}/var.tar.gz)
+if [[ $? -ne 0 ]]; then
+    echo "Error: restoring database"
+    exit 111
+fi
+(cd /zones/$ZONE/root/opt/smartdc/usageapi/config; \
+    tar xzbfE 512 ${TARGET_DIR}/${ROLE}/config.tar.gz)
+if [[ $? -ne 0 ]]; then
+    echo "Error: restoring configuration"
+    exit 112
+fi
+
+echo "All done!!!"
 exit 0
