TOOLS-278: enable SDC service data dump and upload to manta

diff --git a/zones/sdc/setup b/zones/sdc/setup
--- a/zones/sdc/setup
+++ b/zones/sdc/setup
@@ -23,12 +23,30 @@ mkdir -p /var/smartdc/sdc
 # Note: we do NOT want the $role/node_modules/.bin dir on the PATH because
 # we install 'node-smartdc' there to have it available, but we don't want
 # all those 'sdc-*' commands on the default PATH.
-echo "" >>/root/.bashrc
-echo "export MANPATH=\${MANPATH}:/opt/smartdc/${role}/man" >>/root/.bashrc
-echo "export PATH=/opt/smartdc/$role/bin:/opt/smartdc/$role/build/node/bin:\$PATH" >>/root/.bashrc
+echo "" >>/root/.profile
+echo "export MANPATH=\${MANPATH}:/opt/smartdc/${role}/man" >>/root/.profile
+echo "export PATH=/opt/smartdc/$role/bin:/opt/smartdc/$role/build/node/bin:\$PATH" >>/root/.profile
+echo '[[ -f $HOME/.sdc_mantaprofile ]] && source $HOME/.sdc_mantaprofile' >>/root/.profile
 
 # run the configuration
 /opt/smartdc/bin/configure || fatal "unable to configure"
+
+# Setup crontab
+crontab=/tmp/$role-$$.cron
+crontab -l > $crontab
+[[ $? -eq 0 ]] || fatal "Unable to write to $crontab"
+echo '' >>$crontab
+echo '0 * * * * /opt/smartdc/sdc/tools/dump-sdc-svc-data.sh >>/var/log/dump-sdc-svc-data.log 2>&1' >>$crontab
+echo '10 * * * * /opt/smartdc/sdc/tools/upload-sdc-svc-data.sh >>/var/log/upload-sdc-svc-data.log 2>&1' >>$crontab
+crontab $crontab
+[[ $? -eq 0 ]] || fatal "Unable import crontab"
+rm -f $crontab
+
+# Log rotation for those sdc-svc-data scripts.
+logadm -w sdc-svc-data -C 3 -c -s 1m '/var/log/*-sdc-svc-data.log'
+
+# Install Amon probes for the sdc zone.
+TRACE=1 /opt/smartdc/sdc/tools/sdc-amon-install
 
 touch /var/svc/setup_complete
 echo "setup done"
